nvim-neo-tree/neo-tree.nvim

README.md
doc/neo-tree.txt
lua/neo-tree.lua
lua/neo-tree/defaults.lua
lua/neo-tree/sources/buffers/init.lua
lua/neo-tree/sources/common/commands.lua
lua/neo-tree/sources/filesystem/defaults.lua
lua/neo-tree/sources/filesystem/init.lua
lua/neo-tree/sources/filesystem/lib/filter.lua
lua/neo-tree/ui/inputs.lua
lua/neo-tree/ui/popups.lua
lua/neo-tree/ui/renderer.lua
lua/neo-tree/utils.lua
plugin/neo-tree.vim

Closes #8 , fixes #15, and also fixes issues with using configuration options which no one has reported yet.

Add floating window option

---

doc/neo-tree.txt
lua/neo-tree/sources/filesystem/README.md
lua/neo-tree/sources/filesystem/components.lua
lua/neo-tree/sources/filesystem/defaults.lua
lua/neo-tree/ui/highlights.lua
lua/neo-tree/ui/renderer.lua

Initial draft of the feature. What do you think?
Closes #53.

feat(filesystem): add symbolic link target, closes #53

---

doc/neo-tree.txt
lua/neo-tree/log.lua
lua/neo-tree/sources/filesystem/lib/filter_external.lua

also use schedule_wrap log statements to the console. closes #48

fix(files): fixes #48, test for max-results support in fd before using

---

doc/neo-tree.txt
lua/neo-tree.lua
lua/neo-tree/defaults.lua
plugin/neo-tree.vim
tests/init_follow_current_file.lua
tests/mininit.lua
tests/neo-tree/sources/filesystem/filesystem_netrw_hijack_spec.lua

This still needs documentation, but putting up now for discussion. This is related to issues #23, #135, #133, #121.

feat(files): make netrw hijack configurable, allow disable

---

doc/neo-tree.txt
lua/neo-tree.lua
lua/neo-tree/events/init.lua

feat: add `VIM_COLORSCHEME`

---

lua/neo-tree/sources/manager.lua

Rework of #178 against `main` branch

fix(files): set tree root correctly when revealing in split

---

.github/workflows/ci.yml
Makefile
README.md
doc/neo-tree.txt
lua/neo-tree.lua
lua/neo-tree/command/completion.lua
lua/neo-tree/command/init.lua
lua/neo-tree/command/parser.lua
lua/neo-tree/defaults.lua
lua/neo-tree/deprecations.lua
lua/neo-tree/sources/filesystem/init.lua
lua/neo-tree/sources/manager.lua
lua/neo-tree/ui/renderer.lua
lua/neo-tree/utils.lua
plugin/neo-tree.vim
tests/helpers/util.lua
tests/helpers/verify.lua
tests/neo-tree/sources/filesystem/filesystem_netrw_hijack_spec.lua

BREAKING CHANGE: "split" position renamed to "current"

feat!: all commands deprecated in favor of a new, more flexible Neotree command

---

lua/neo-tree/utils.lua

commit 0a6ea743d51829c3ef3413eb172a26ff7a25e9ff
Author: Shane Hird <shane.hird@csgicorp.com>
Date:   Mon Mar 28 09:02:54 2022 +1000
Special handling for E325
commit b3c3cbc9b1e2bf9e07f5acf44f1d0c279aefb745
Author: smhc <shanehird@gmail.com>
Date:   Sun Mar 27 13:23:14 2022 +1000
Suppress non-critical errors on opening file (e.g E325)

fix: Suppress non-critical errors on opening file (e.g E325)

---

README.md
doc/neo-tree.txt
lua/neo-tree/defaults.lua
lua/neo-tree/setup/init.lua
lua/neo-tree/sources/common/components.lua
lua/neo-tree/sources/common/container.lua
lua/neo-tree/sources/filesystem/init.lua
lua/neo-tree/sources/manager.lua
lua/neo-tree/ui/highlights.lua
lua/neo-tree/ui/renderer.lua
lua/neo-tree/utils.lua

https://github.com/nvim-neo-tree/resources/blob/main/videos/Neo-tree%20container%20character%20fading.mp4

feat: add container component, right align status symbols, fade truncated names, closes #208

---

doc/neo-tree.txt
lua/neo-tree/setup/init.lua
lua/neo-tree/ui/highlights.lua

For more visual customisation.

feat: add highlight EndOfBuffer group

---

lua/neo-tree/command/init.lua
lua/neo-tree/defaults.lua
lua/neo-tree/events/queue.lua
lua/neo-tree/git/status.lua
lua/neo-tree/sources/common/commands.lua
lua/neo-tree/sources/filesystem/init.lua
lua/neo-tree/sources/manager.lua
lua/neo-tree/ui/renderer.lua

- refactor: try to speed up render
- feat: allow disabling resize timer
- refactor: move all tree:render calls to a central location
- fix: turn off undo in tree buffers, fixes memory leak and maybe speed issues

performance work

---

README.md

Minor niggle on its vs it's contraction in README

fix possessive its

---

lua/neo-tree/git/ignored.lua
lua/neo-tree/sources/common/commands.lua

fix gitignore on Windows and File Nesting

---

lua/neo-tree/utils.lua

fix diagnostics lookup on Windows

---

lua/neo-tree/setup/init.lua
lua/neo-tree/sources/filesystem/commands.lua
lua/neo-tree/sources/filesystem/lib/fs_scan.lua
lua/neo-tree/utils.lua

- fix(files): remove parallel execution from async scan, related to #286, #287
- fix(files): revert async_scan changes, fix path issues for windows
- fix(files): fix split_path for drive root on windows
- fix(files): fix split_path for drive root on windows, take 2
- fix(files): fix split_path for drive root on windows, take 3

fix async scan issues

---

README.md
doc/neo-tree.txt
lua/neo-tree/defaults.lua
lua/neo-tree/sources/common/components.lua
lua/neo-tree/sources/common/file-items.lua
lua/neo-tree/ui/highlights.lua
lua/neo-tree/utils.lua

as the title, only Windows support

feat: Windows hidden files/directories

---

README.md
lua/neo-tree/defaults.lua
lua/neo-tree/setup/init.lua
lua/neo-tree/sources/common/container.lua
lua/neo-tree/ui/highlights.lua

Also includes the fix for #291 .

fix: reset faded hl cache on colorscheme change, allow disable char fading, fixes #311

---

lua/neo-tree/sources/buffers/init.lua
lua/neo-tree/sources/git_status/init.lua

fix: handle reveal for `buffers` and `git_status` sources

---

tests/neo-tree/ui/icons_spec.lua
tests/utils/init.lua

Rebased on:
- https://github.com/nvim-neo-tree/neo-tree.nvim/pull/431
- https://github.com/nvim-neo-tree/neo-tree.nvim/pull/437

test(ui): add tests for icons

---

lua/neo-tree/ui/selector.lua

Hi, I am the author of #427 .
I added type hints and function descriptions to the code.
Best,
@pysan3

feat: added type hints and function description to all functions in `ui.selector`

---

README.md
doc/neo-tree.txt
lua/neo-tree/defaults.lua
lua/neo-tree/ui/highlights.lua
lua/neo-tree/ui/selector.lua
tests/utils/fs.lua

I think this is ready for release now. I decided against getting too complicated with the winbar right now.

source selector, part 3

---

lua/neo-tree/git/status.lua
lua/neo-tree/setup/init.lua
lua/neo-tree/sources/buffers/lib/items.lua
lua/neo-tree/sources/common/file-items.lua
lua/neo-tree/sources/filesystem/commands.lua
lua/neo-tree/sources/filesystem/init.lua
lua/neo-tree/sources/filesystem/lib/fs_scan.lua
lua/neo-tree/sources/filesystem/lib/fs_watch.lua
lua/neo-tree/sources/git_status/lib/items.lua
lua/neo-tree/sources/manager.lua

- refactor(filesystem): cleanup while searching for memory leak
- fix(filesystem): fix memory leak in file watchers, part of #393

Fix memory leak and refactor file watchers

---

doc/neo-tree.txt

Simple docs change.
See #356 and #382

Fix issue #356: Improve documentation for mappings

---

lua/neo-tree/sources/common/commands.lua
lua/neo-tree/sources/common/preview.lua

- refactor: make Preview a singleton
- fix(preview): fixes #521, "preview window freezes when opening new folder"

fix preview after lazy loading folder

---

lua/neo-tree/utils.lua

This fixes https://github.com/nvim-neo-tree/neo-tree.nvim/issues/576 for me.

Fix new window orientation when Neo-tree is only window

---

README.md
scripts/test.sh

The repositories have been moved.

Rename references to kyazdani42 repositories

---

lua/neo-tree/setup/init.lua
lua/neo-tree/sources/common/preview.lua
lua/neo-tree/ui/highlights.lua
lua/neo-tree/ui/popups.lua

feat(ui): add NeoTreeFloatNormal highlight group

---

lua/neo-tree/events/queue.lua
tests/neo-tree/events/queue_spec.lua

fixes #631, required by PR #625

fix(events): return result from event when `{ handled = true }`

---

lua/neo-tree/ui/renderer.lua

fix(renderer): add checks to make sure tree is still visible throughout renderer module

---

lua/neo-tree/setup/init.lua

fix: prevent error caused by not using all built-in sources

---

README.md

removed the additional "s" outside the syntax

docs: removed the additional "s"

---

lua/neo-tree/setup/init.lua

fix: save and restore prior window options when using position="current"

---

lua/neo-tree/setup/init.lua

Improvement for #684. This prevents the restore from clobbering settings that may be applied to the new buffer by a
filetype autocmd. The new strategy restores the settings **before** the neo-tree buffer leaves the window.

fix: move window setting restore to more precise BufWinLeave autocmd

---

lua/neo-tree/utils.lua

fix: do not open files in floating windows

---

README.md

Nothing to fancy, just a comma, may you will see me again!
Good job with neo-tree! 💝

docs: fix missed comma

---

.luarc.json

This is the config file for [lua-language-server](https://github.com/LuaLS/lua-language-server/wiki/Configuration-File#luarcjson)

chore: add .luarc.json

---

lua/neo-tree/sources/common/commands.lua

fix(filesystem): fix get_folder_node logic

---

lua/neo-tree/sources/filesystem/lib/fs_actions.lua

fix(filesystem): prevent infinite recursion by copying folder to itself, fixes #795

---

lua/neo-tree/ui/renderer.lua

fix: always display in the original window when position=current

---

doc/neo-tree.txt

Resolving documentation issue #891

Fix(Documentation) : adding quotation to fix issue #891

---

README.md

docs(readme): fix broken icons of Nerd Fonts v3

---

lua/neo-tree/defaults.lua

Added support for [edgy.nvim](https://github.com/folke/edgy.nvim)
I've also fixed the filetype for trouble.

feat(config): added support for edgy.nvim and fixed trouble.nvim ft

---

lua/neo-tree/sources/common/components.lua

fix: lowercase file extension when looking up icon

---

CONTRIBUTING.md
README.md

docs: update README for 3.0

---

README.md
doc/neo-tree.txt
lua/neo-tree/defaults.lua

Sorry for the PR spam, I noticed this other typo immediately after you merged the previous PR 😂

docs: fix help tags for custom commands and mappings

---

lua/neo-tree/ui/renderer.lua

Changes `add_blank_line_at_top` implementation as suggested by @MunifTanjim in #972. Also fixes the issues for the `document_symbols` source in #879.

fix(config): change add_blank_line_at_top implementation

---

lua/neo-tree/sources/filesystem/init.lua
lua/neo-tree/sources/filesystem/lib/fs_scan.lua
lua/neo-tree/ui/renderer.lua
tests/neo-tree/command/command_spec.lua
tests/neo-tree/ui/icons_spec.lua
tests/utils/init.lua
tests/utils/verify.lua

feat(filesystem): show window immediately without waiting for async scan

---

lua/neo-tree/utils.lua

fix: make ffi/LuaJIT an optional dependency

---

lua/neo-tree/utils/init.lua

#1148 accidentally broke 0.8 and earlier - here we add a nil check
I made sure to test and it works 0.8.3

Add a nil check to vim.diagnostic.is_disabled

---

lua/neo-tree/collections.lua

fix: set global variables to local

---

lua/neo-tree/ui/renderer.lua

Fixes bug introduced by https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1280.

fix(renderer): fix Neotree focus/show toggle behaviour

---

lua/neo-tree/ui/selector.lua

Fixes: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1286

fix(selector): selector layouts cannot handle when not enough width

---

doc/neo-tree.txt

Noticed mistake on docs when reading them today :)
Thanks for this awesome plugin and have a nice weekend for the maintainers!

fix(docs): use proper lua syntax & vim.keymap api

---

lua/neo-tree/utils/init.lua

`vim.diagnostic.is_disabled` is now deprecated in nvim 0.10 - neovim/neovim#28227

fix: deprecated use of vim.diagnostic.is_disabled

---

doc/neo-tree.txt

I went through the neotree help doc to set up and customize my neotree.
I want to leave the Documentation in a better place after reading.
These are just minor discrepancies I noticed.

doc: minor updates to help doc

---

lua/neo-tree/sources/common/file-nesting.lua
lua/neo-tree/sources/common/help.lua

close https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1466

fix: add local scope

---

lua/neo-tree/sources/common/preview.lua

image.nvim updated their hijack implementation, we should just rely on its bufwinenter autocmd which follows image.nvim's configurable patterns, instead of hijacking the buffer ourselves.
Closes #1373

fix(preview): update image.nvim integration

---

.github/ISSUE_TEMPLATE/bug_report.yml

Removes implicit lazy-loading, uses a smaller repro.lua courtesy of lazy.nvim, and also updates some older references.

chore(issue): update the bug report template

---

.github/ISSUE_TEMPLATE/bug_report.yml
README.md
lua/neo-tree/sources/common/preview.lua

fix(preview): setup image.nvim if needed

---

lua/neo-tree/sources/common/preview.lua

fix(preview): use scratch buffer for float to stop side effects

---

.github/ISSUE_TEMPLATE/bug_report.yml

Was being misparsed, bug report template should work now

chore: properly indent bug report template

---

lua/neo-tree/sources/document_symbols/lib/symbols_utils.lua

A proposed fix for issue #1678

fix(document_symbols): parse preview range

---

lua/neo-tree/setup/init.lua

fix(setup): always apply window settings

---

README.md

docs(README): mention nvim-lsp-file-operations

---

.github/workflows/ci.yml
lua/neo-tree/utils/init.lua

- test multiple neovim versions
- use bin instead of appimage (really for no reason other than it mirrors plenary's example more)
- fix errors

ci: update action

---

lua/neo-tree/defaults.lua

found this small thing when I was trying to debug my custom source.

docs: update show logs comment in defaults.lua

---

lua/neo-tree.lua
lua/neo-tree/setup/netrw.lua
plugin/neo-tree.lua

fix(setup): explicitly specify path to hijack when possible

---

lua/neo-tree/sources/common/commands.lua
lua/neo-tree/sources/common/preview.lua
lua/neo-tree/ui/renderer.lua

fix(mappings): fallback for focus_preview

---

README.md
doc/neo-tree.txt
lua/neo-tree/sources/common/components.lua

fix(diagnostics): add fallback to signs on nvim v0.10+

---

lua/neo-tree/sources/filesystem/lib/fs_scan.lua

fix(filesystem): read all files from large directories

---

lua/neo-tree/sources/common/filters/init.lua
lua/neo-tree/sources/filesystem/lib/filter.lua
lua/neo-tree/types/config/filesystem.lua

fix(fuzzy): add close command to all fuzzy finders

---

lua/neo-tree/ui/renderer.lua

fix(mappings): revise error for invalid mappings

---

lua/neo-tree/health/init.lua

closes #289 
there's more work to do on the validation but should get at least a few misconfigurations out of the way

feat: add healthcheck

---

lua/neo-tree/sources/filesystem/lib/fs_scan.lua

fix(filesystem): fix infinite loop on synchronous file scan

---

lua/neo-tree/setup/init.lua

Closes #1818 
going to leave open for a bit while waiting for original commenter to respond

fix: ignore `close_if_last_window` when exiting popups

---

lua/neo-tree/defaults.lua
lua/neo-tree/health/init.lua
lua/neo-tree/sources/common/components.lua
lua/neo-tree/sources/common/file-items.lua
lua/neo-tree/sources/filesystem/init.lua
lua/neo-tree/types/components.lua
lua/neo-tree/ui/renderer.lua

feat(renderer): allow children of filtered to retain normal hls

---

README.md

Fix checkout property in mini.deps install snippet

docs(README): fix mini.deps instructions

---

tests/neo-tree/ui/icons_spec.lua
tests/utils/init.lua

should make some tests more reliable

test: wait for changedtick before asserting buffer changes

---

lua/neo-tree/ui/inputs.lua

fix(inputs): automatically enter insert mode when confirming

---

lua/neo-tree/log.lua

fix(log): fix line debug information

---

lua/neo-tree.lua
lua/neo-tree/log.lua
lua/neo-tree/setup/init.lua
tests/neo-tree/log_spec.lua

Also added a test for the log regression

fix(log): set log settings immediately, fix no-op logic
