- lua/neo-tree/sources/filesystem/commands.lua
- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
Toggle the state.filters.(show_hidden|respect_gitignore) flags, instead
of setting them on the root state object.
> fix(files): fixes #71, toggle the correct flags.

- lua/neo-tree/sources/filesystem/commands.lua
manager.show only shows the tree if not already show, and doesn't re-scan.
> fix #69 toggling ignores and hidden

- lua/neo-tree/sources/manager.lua
- lua/neo-tree/ui/renderer.lua
> fix(render): Ensure *Show and *Focus commands maintain the previous cursor position within the tree

- lua/neo-tree/git/init.lua
- lua/neo-tree/sources/buffers/init.lua
- lua/neo-tree/sources/filesystem/README.md
- lua/neo-tree/sources/filesystem/init.lua
- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
- lua/neo-tree/sources/git_status/lib/items.lua
- lua/neo-tree/ui/highlights.lua
- lua/neo-tree/utils.lua
Plenary's scandir only checks for .gitignore files in the directories it
scans. Since directories are only scanned when opened any .gitignore in
any parent directory isn't applied.
Implements handling of .gitignore files anywhere in the tree. The parsing
and checking logic is copied from the Plenary implementation.
> fix(files): fixes #78, correctly handle .gitignore

- lua/neo-tree/sources/manager.lua
- lua/neo-tree/utils.lua
Fixes #97.
Add `normalize_path` and `is_subpath` to utils.lua, and use then when checking if file is in the cwd. Currently `normalize_path` only uppercase the drive letter in Windows.
> fix: fixes #97, normalize path when checking subpath

- Makefile
- tests/helpers/util.lua
- tests/helpers/verify.lua
- tests/mininit.lua
@cseickel I split this out from the work I am doing on other branches as it seems to be in a relatively good state, and it would be beneficial to have sooner rather than later.
As an overview of what is here:
- Top level `Makefile` so you can just simply `make test` and run them as you please (also `make format` to run  `stylua`)
- Utility function(s) to setup/teardown a "test filesystem" to do whatever you want in
- Verification functions that help with the fact that a lot of the functions in `neo-tree` are async, so by default if we do something like `vim.cmd("NeoTreeFocus")` and then try to verify stuff, the verification is almost always going to fail as it happens too soon.
To show what this ends up looking like:
```lua
local util = require("tests.helpers.util")
local verify = …
```
> feat(tests): Add baseline testing using Plenary's Busted hooks

- lua/neo-tree/git/ignored.lua
- lua/neo-tree/utils.lua
> fix: windows gitignore

- doc/neo-tree.txt
- lua/neo-tree/ui/highlights.lua
- lua/neo-tree/ui/popups.lua
This fixes the issue described in https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/35. I cleaned everything up and updated the documentation accordingly.
If there's something missing please let me know!
Best regards!
> add NeoTreeFloatTitle highlight group

- README.md
- doc/neo-tree.txt
- lua/neo-tree/defaults.lua
- lua/neo-tree/setup/init.lua
- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/sources/common/components.lua
- lua/neo-tree/sources/common/file-items.lua
- lua/neo-tree/sources/common/file-nesting.lua
- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
- lua/neo-tree/ui/highlights.lua
- lua/neo-tree/ui/renderer.lua
- lua/neo-tree/utils.lua
> feat: file nesting

- lua/neo-tree/command/init.lua
- tests/helpers/util.lua
- tests/neo-tree/command/command_current_spec.lua
This PR fixes a bug where the tree will not open if `reveal_force_cwd` is given but the cwd doesn't need to change. i.e. the cwd is already a parent of the file being revealed. As you can see from the changes, the bug was just caused by an if branch being taken and then not doing anything.
I've added a unit test for this case and also tested manually.
> fix: handle reveal_force_cwd correctly when cwd doesn't need to change

- CONTRIBUTING.md
- lua/neo-tree/sources/common/components.lua
With this, `last_indent_marker` can be more than one display cell wide. The difference is subtracted from the indent level.
```lua
indent = {
indent_size = 4,
last_indent_marker = "└──",
},
```
(I also fixed some typos, I can make a different PR for this if you want)
> feat: support variable `last_indent_marker` width

- README.md
- doc/neo-tree.txt
- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/buffers/commands.lua
- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/sources/filesystem/commands.lua
- lua/neo-tree/sources/git_status/commands.lua
I'd like to add support for opening a file from the filesystem source in a new tab.
> feat: add tabnew command for opening via a new tab.

- doc/neo-tree.txt
- lua/neo-tree/setup/init.lua
- lua/neo-tree/ui/highlights.lua
Hi! First of all, thank you for making this awesome plugin.
I really like `neo-tree`, but wished there were more options for customizing the colors.
Please let me know if there is any problem 😸
> feat: add highlight group

- README.md
- doc/neo-tree.txt
- lua/neo-tree/command/completion.lua
- lua/neo-tree/command/init.lua
- lua/neo-tree/command/parser.lua
- lua/neo-tree/git/status.lua
- lua/neo-tree/sources/buffers/init.lua
- lua/neo-tree/sources/common/components.lua
- lua/neo-tree/sources/filesystem/init.lua
- lua/neo-tree/sources/git_status/lib/items.lua
- lua/neo-tree/sources/manager.lua
I'd like to add support for changing the git base.
With the current implementation it just defaults to `HEAD`, but there are cases where it would be nice to see the diff against other bases as well.
For example, when you review a pull request, or you are working on a feature branch and want to compare it against the main branch.
The implementation is not super complex, instead of using `git status . --porcelain=v1`, you use `git -C . diff --name-status HEAD --` where `HEAD` can be any commit/branch.
You get the same information, but the formatting of the output is a little bit different.
This is just a hacky PoC, so you can try with setting `vim.g.git_base` to different values. I wanted to ask if you are okay with this, before I make a proper PR.
Also `vim.g.git_base` needs to be handled …
> feat: support git base

- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
This is an implementation of the comment in https://github.com/nvim-neo-tree/neo-tree.nvim/issues/236#issuecomment-1088210652, pasting the algorithm for future reference:
```
local function async_scan(context, callback /* new */)
for every path in context.paths_to_load
async_scan(path) ->
scan.scan_dir_async(parent) -> 
wait for on_exit callback ->  increase counter and call `callback` when all the paths in context_paths are done
```
> Make async_scan scan each opened directory asynchronously

- doc/neo-tree.txt
- lua/neo-tree/setup/init.lua
- lua/neo-tree/ui/highlights.lua
Hi! recently I found one missing part while customizing the theme of the neo-tree.
Like the picture above, The background color of the neo-tree can be changed using `NeoTreeNormal`. And this overrides `Normal`.
However, because there were no highlight groups defined in the neo-tree for `SignColumn`, `NeoTreeNormal` was unable to create a consistent theme.
> fix: missing signcolumn highlight group

- lua/neo-tree/git/ignored.lua
- lua/neo-tree/git/utils.lua
- chore: add extra logging for giti ignored work, part of #236
- fix: remove git root lookup from git check ignored, may fix #236
> 236 gitignored slowdown

- lua/neo-tree/git/status.lua
I can't use `:Neotree git_status`
The print is the `line_parts` variable
> fix: skip git warnings

- doc/neo-tree.txt
- lua/neo-tree/defaults.lua
- lua/neo-tree/setup/init.lua
Discussion: https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/265
> feat: add config - disable_default_mappings

- doc/neo-tree.txt
- lua/neo-tree/setup/init.lua
- lua/neo-tree/ui/highlights.lua
Fix https://github.com/nvim-neo-tree/neo-tree.nvim/issues/328
This PR only adds the `NeoTreeWinSeparator` so that pre 0.7 users can continue using their setup.
In the future, `NeoTreeVertSplit` could be considered for removal? And the local `winhighlight` option would override both `WinSeparator` and `VertSplit` with `NeoTreeWinSeparator`, thus allowing pre 0.7 and post 0.7 users to work
> Add NeoTreeWinSepartor hl

- lua/neo-tree/sources/git_status/commands.lua
By using single quotes, commit messages can contain special characters like ` (backtick) without being interpreted.
For example, providing [this is a \`test\`] without brackets results now in [this is a ] instead of [this is a `test`].
> Change `git commit` quotes context

- README.md
- doc/neo-tree.txt
- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
1. This PR fixes the issue I introduced wrt the show_path option I mentioned in my previous PR: https://github.com/nvim-neo-tree/neo-tree.nvim/pull/367#issuecomment-1146204360
2. Also tried to improve documentation a little bit, as per comment on the previous PR.
3. And when writing this documentation I realized that my previous change, from plenary Path.copy() to vim.loop.fs_copyfile(), removed the ability to copy a directory (recursively), so I reverted that change back to using Path.copy(), and also did some digging into why it silently failed with my usecase described in the previous PR (copying a file to a non-existing dir):
- The way the Path.copy() error was checked was incomplete, if the call to copy() succeeds, then the result a (potentially nested) table of Path instances as …
> Fix boolean expression bug

- lua/neo-tree/setup/init.lua
A recent change added a check that the nvim version is >= 0.7 to use the WinSeparator highlight. The code for the check was
`if vim.version().major >= 7`, but it should use `minor` instead of `major` since '7' is the minor version.
> Use correct method to check nvim version is >= 0.7

- lua/neo-tree/ui/renderer.lua
Disable `colorcolumn` by default. Closes #390.
> fix(ui/renderer.lua): disable colorcolumn by default

- lua/neo-tree/sources/common/file-nesting.lua
> fix(file-nesting): adding multiple file types (#334)

- README.md
Hi, noticed a small mistake in the readme :)
> fix(doc): Fixed README, description referring to a wrong keyword

- lua/neo-tree/sources/common/commands.lua
Currently, the following commands do not invoke the `file_opened` / `file_open_requested` event_handlers.
- `open_with_window_picker`
- `split_with_window_picker`
- `vsplit_with_window_picker`
I would like them to trigger the same event_handlers as their corresponding builtin commands: `open`, `split`, `vsplit`.
If this is not a feature you are supporting, could you consider defining a different command name that mimics this feature? Like, `open_with_window_picker_and_event_handler` perhaps?
Love to hear your thoughts, thanks
pysan3
> feat(commands): Make `"_with_window_picker"` commands also invoke event_handlers

- lua/neo-tree/ui/renderer.lua
Hi! I think it would be better if `signcolumn` was disabled by default.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> feat: disable signcolumn by default

- README.md
The tag in the window picker plugin is prefixed with `v` if you don't have it, packer won't install the correct tags
> docs(README): fix incorrect window picker tag

- lua/neo-tree/sources/common/container.lua
As you can see in #408 , by disabling `signcolumn`, the width of the window changes.
I noticed a gap between icons and the edge on the right side. (See screenshots in https://github.com/nvim-neo-tree/neo-tree.nvim/pull/408#issuecomment-1179905051 )
I think this can be fixed by changing this line.
Best,
@pysan3
> fix: remove extra space on right related to #408

- lua/neo-tree/ui/highlights.lua
- lua/neo-tree/ui/popups.lua
- lua/neo-tree/ui/renderer.lua
If namespace id is not provided `nui.nvim` uses it's fallback namespace that is shared for other plugins using `nui.nvim`. It's better to use own namespace id.
Also, it is needed for testing.
> feat(ui): use own namespace id

- README.md
- lua/neo-tree/command/parser.lua
- lua/neo-tree/defaults.lua
- lua/neo-tree/ui/renderer.lua
Some external sources, for example my [diagnostic source](https://github.com/mrbjarksen/neo-tree-diagnostics.nvim), may benefit from opening windows at the top or bottom positions. This PR enables these positions and sets the default height of top and bottom windows to 15 rows.
> feat: enable opening at top and bottom positions

- lua/neo-tree/utils.lua
The function `utils.open_file` smartly uses the command `b` instead of `edit` to avoid some overhead if the file is loaded in a buffer. The definition of `open` in `neo-tree.sources.common.commands` (and by extension, the `open` command in all built-in sources) fails to take advantage of this, however, by using `e` instead of `edit`. 
This PR fixes this behavior, electing to accept `e` in addition to `edit`, to look for an open buffer.
> fix(command): use `b` when open_cmd is `e` instead of `edit`

- lua/neo-tree/ui/popups.lua
Fixes No. 2 of #439 
There are always chances for improvement. When you see one here, I would love if you let me know.
> fix: dialogs outside ui when tree pos is right

- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/manager.lua
- lua/neo-tree/ui/highlights.lua
- lua/neo-tree/ui/renderer.lua
- lua/neo-tree/ui/selector.lua
This is related to #427 #425 
I'll use this PR for further refinement of the source selector feature. Here is the current default look:
Next up is to:
EDIT: These two will be handled separately. I think I'd like to refactor, move more config into the sources, and allow for other functionality besides just source selectors in the winbar.
> source selector refinement

- doc/neo-tree.txt
Hi again, I am the author of https://github.com/nvim-neo-tree/neo-tree.nvim/pull/427.
I added the documentation for source selector in the help page.
Could you have a look though the grammar and English because I am not a native speaker?
Thanks in advance,
@pysan3
> add documentation for source selector

- README.md
- doc/neo-tree.txt
- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/file-items.lua
Add support to hide files by comparing to glob of full path
> Hide by pattern path

- lua/neo-tree/ui/renderer.lua
I noticed `"(1 hidden items)"` in the tree and this PR aims to fix the pluralization problem.
PS: Thanks a lot for this awesome plugin! It's amazing!
> fix: fix pluralization in "hidden items" hints

- lua/neo-tree/log.lua
I set log_level='warn' because the notifications are noisy. But when open nvim, it always show a notification like below.
It is unnecessary, because user know what configuration written.
> Do not notify log level when user set log_level='warn'

- lua/neo-tree/command/completion.lua
fix "%" in command line completion
``` lua
-- minimal_init.lua
vim.opt.runtimepath:append('~/.local/share/nvim/site/pack/p/start/plenary.nvim/')
vim.opt.runtimepath:append('~/.local/share/nvim/site/pack/p/start/nui.nvim/')
vim.opt.runtimepath:append('~/.local/share/nvim/site/pack/p/start/neo-tree.nvim/')
vim.cmd("runtime plugin/neo-tree.vim")
require("neo-tree").setup({})
```
1. nvim --clean
2. luafile minimal_init.lua
3. :NeoTree %\<Tab>
no errors.
error occured.
```
E5108: Error executing lua ...start/neo-tree.nvim//lua/neo-tree/command/completi
on.lua:60: malformed pattern (ends with '%')
stack traceback:
[C]: in function 'find'
...start/neo-tree.nvim//lua/neo-tree/command/completion.lua:60: in funct
ion <...start/neo-tree.nvim//lua/neo-tree/command/completion.lua:49>
```
- windows 10 …
> fix: plain match "%" in command line completion

- lua/neo-tree/ui/selector.lua
Hi, I think this is enough to fix #565
I'm still investigating why `action = 'show'` fails on a floating window.
- `prev_source, next_source` (i.e. `<`, `>`) uses `action = 'focus'` instead
- Works without fix for `config.window.position = 'left'` and all other options except `'float'`
- Switching to other sources has no problem even with `'float'`
I thought that `action = 'show'` will cache or whatever and speed up the switch, but looking at the code, I don't think there are any downsides by doing it this way. (And this is how `<`, `>` was implemented in the first place, which did not cause any problem)
> fix: Clickable filesystem source winbar component closes neo-tree immediately

- README.md
`quickfix` window filetype is `qf`,
`quickfix` window buftype is `quickfix`,
so move to buftype.
thanks.
> fix: nvim-window-picker buftype rules

- lua/neo-tree/command/init.lua
When opening a new neo-tree window with the `current` position, do not close all other `current` windows.
This allows having multiple `current` windows side-by-side on the same tabpage.
It was possible before with the following combination (open neo-tree in one buffer, then split it):
```
:e .<CR>:vs
```
This opened two neo-tree windows side-by-side (when `hijack_netrw_behavior` was set to `open_current`).
https://user-images.githubusercontent.com/889383/200114060-d441d519-240c-458d-a1c6-5fd47fbd44ff.mp4
However, when trying to it the other way around (open two buffers side by side, open neo-tree in one of them, then switch to the other buffer and open neo-tree in that one):
```
:vs<CR>:Neotree position=current<CR><C-W>p:Neotree position=current
```
Opening the second neo-tree window …
> fix: opening multiple current neo-tree windows

- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
When renaming or moving files/directories, neo-tree used to change the name of renamed buffers while retaining the same buffer numbers. It did not delete the old buffers and open new ones for editing.
This ended up crashing Neovim in the following scenario:
* a `BufWritePre` autocmd was created to call `vim.lsp.buf.format({ async = false })`
* there was an LSP client registered for the buffer
* the buffer was opened and then put in the background (e.g. by `:Neotree position=current`)
* the file was renamed/moved in neo-tree
The operation that caused the Neovim crash was the `silent! write!` that neo-tree executes on the buffer right after it is renamed. During that write, synchronous formatting is attempted in the `BufWritePre` autocmd.
My assumption is that the LSP server does not get a …
> fix: crash when renaming files that have sync-formatting autocmd

- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/sources/common/container.lua
- lua/neo-tree/ui/renderer.lua
Hi, I love the extensibility of this plugin.
I think this feature (#547) is quite useful, especially when you want to peek a filename or dealing with very deep file structures.
I tried to implement this feature with the following configs and I would like to hear your opinions.
Default: `false`
Usually, long file names and deep hierarchy folders (by the indents) are truncated and goes underneath modified symbols etc. However, by setting this to `true`, the filename is not truncated and instead, the window width is expanded (ignoring `window.width` option) to show the whole content.
|Default|`window.auto_expand_width = true`|
|-|-|
|![image](https://user-images.githubusercontent.com/41065736/197484689-62cae1b9-d718-4d61-945f-a9e3cfa78a6b.png)|![image](https://user-images.githubusercontent.co …
> feat: Auto Width or Full Name Under Cursor (related to #547)

- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
Replace `uv.fs_scandir` and `uv.fs_scandir_next` with their async alternatives, `uv.fs_opendir` and `uv.fs_readdir`
Fix: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/609
> fix(filesystem): make `async_scan` asynchronous

- lua/neo-tree/sources/common/container.lua
- lua/neo-tree/ui/renderer.lua
Should fix https://github.com/nvim-neo-tree/neo-tree.nvim/issues/624.
For more info and discussion, please read the above issue.
> fix: auto_expand_width gets caught in infinite loop and hangs neovim (#624)

- lua/neo-tree/setup/init.lua
- lua/neo-tree/utils.lua
This fixes the situation described in #605 
The new strategy is to detect if there is an unnamed modified buffer, and if there is, it will open it and show a warning message.
> fix: cancel close_if_last_window if there is an unnamed modified buffer, fixes #605

- lua/neo-tree/sources/common/container.lua
- lua/neo-tree/ui/renderer.lua
This adds an explicit "pre-render" phase that is used for both `auto_expand_width` and `position="current"` which can figure out **exactly** how much width is "wanted" by the longest node.
Since it is known when we are in a pre-render vs final render phase, I am able to store the computed NuiLine from pre-render and reuse it if it turns out that the width does not need to change. It still has to draw twice, but at least it doesn't have to compute all of the individual nodes twice.
This new pre-render phase results in a more precise right aligned column for the "current" postion.
It also explicitly disables character fading in the container when `auto_expand_width` is enabled, which will make it more efficient.
Finally, these changes prevent the possibility of an infinite render loop, …
> fix: remove recursion in auto_expand render

- lua/neo-tree/git/ignored.lua
- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
- tests/neo-tree/ui/icons_spec.lua
This PR introduces an alternative async interface for `git.mark_ignored`. By providing a callback to the function, it will run the git operations via `luv.spawn` instead of `vim.fn.systemlist`.
In the async interface, the files to be checked are fed through the stdin, instead of through the CLI arguments. This is because certain collection of filenames causes `luv` to fail to spawn the git process (maybe because of the length or certain unicode characters?). If there are any performance issues caused by the pipe method, I'll try to investigate further on it.
> fix(git): make `mark_ignored` async

- lua/neo-tree/git/status.lua
- lua/neo-tree/git/utils.lua
- lua/neo-tree/log.lua
- lua/neo-tree/setup/deprecations.lua
- lua/neo-tree/sources/filesystem/lib/filter_external.lua
- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
- lua/neo-tree/sources/filesystem/lib/fs_watch.lua
- lua/neo-tree/ui/highlights.lua
- lua/neo-tree/ui/renderer.lua
- lua/neo-tree/ui/selector.lua
This adds a callback argument to `git.utils.get_repository_root`, which allows the function to be called asynchronously.
Callers are also adjusted so that it respects the `async_git_status` option.
Also, I've been wondering, is it really necessary to have synchronous support at all? As long as the asynchronous version is implemented correctly, I can't imagine a user that would prefer to use the synchronous version. 
Once the async paths are battle-tested and its rough edges polished, what do you think about dropping non-async support in the next major version? I feel that it would simplify the codebase.
> feat(git): async git interface for `get_repository_root`

- lua/neo-tree/setup/init.lua
Small fix to set `cursorlineopt=line` to ensure a visible cursorline when `cursorlineopt=number` is set globally.
> fix: no cursorline when using cursorlineopt=number

- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
Same thing as #644 but when removing an item rather than closing it.
Checked a few other places that window operations are done (specifically `nvim_win_get_buf`) and most don't have as simple of a path forward if the window is not valid, or apply to the Neotree window itself where we are often sure beforehand that it is indeed valid.
> fix(fs_actions): check window valid on close buf

- lua/neo-tree/sources/common/components.lua
- lua/neo-tree/sources/filesystem/components.lua
Fixes #635.
For more information, please read the above issue.
Best,
pysan3
> fix (components): enable using `symlink_target` on all sources

- README.md
- doc/neo-tree.txt
- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
- lua/neo-tree/utils.lua
Hi, big thanks for the nice plugin again.
This PR aims to implement the brace expansion feature just like BASH (probly POSIX compatible?) shell as suggested in #647.
The core implementation is in `require("neo-tree.utils").brace_expand(s)` which handles all expansion and return a list of strings being expanded. If no expansion is found, it returns a one-element list with the raw input.
The calculation is not done by using the shell or anything and is just emulated inside lua, meaning that Windows users can also use this feature with the bash syntax.
I am pretty sure I was able to cover all edge cases but it would be nice if anyone could double check if I hadn't screwed up anything.
The basic syntax of bash brace expansion can be found …
> feat (fs_actions): add brace expansion for creating files / folders

- lua/neo-tree/sources/filesystem/lib/filter.lua
#670 
The titles are inspired by modern file mangers like dolphin. Which use "Filter" for live filtering. "Search" for seraching on submit.
Please let me know if any changes are desired or feel free to submit as co-auth.
> feat: use distinct filter prompt titles

- README.md
- doc/neo-tree.txt
- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/sources/common/preview.lua
#672 
>Once you are in the preview window, it would be nice to add just two extra mappings:
>
>- One to close the window and end preview mode
>- One to move the cursor back to neo-tree
I didn't implement such additional mappings. 
- Moving the cursor back to the neo-tree: I don't think an additional mapping is necessary as this can be done with the present `:Neotree` commands and with vims window movement keys (`<C-w>h` `<C-w>` and the user-defined equivalents to it) etc..
- Close preview: I was not 100% sure about this one. But I also left it out for now, since the window can be closed with the standard commands for closing windows (i.e. `:q`). Users can also assign buffer local commands to close popup windows. But I can certainly see a use case for implementing this to make it specific …
> feat: add focus_preview command

- .github/workflows/ci.yml
- lua/neo-tree/sources/common/components.lua
- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
- lua/neo-tree/ui/renderer.lua
- scripts/test.sh
fixes #683
Adds a message when a folder is empty and the root node is configured to be hidden. This works around glitches when
there are no nodes at all, while offering some feedback rather than just having an empty window.
> fix(filesystem): handle empty folders correctly with hidden root node

- lua/neo-tree/events/queue.lua
If an event handler should be removed (by way of `once = true` or the handler returning `true`), the event queue erroneously skips handling the next node and jumps two nodes ahead. If this is the last event in the queue, this also results in an error (attempt to index a nil value).
> fix(queue): don't go to next node if it has been removed

- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
When pressing `a` into `escape` in neo-tree, I ran into this error, this fixes the issue for me
```
Error executing vim.schedule lua callback: ...eovimPackages/start/neo-tree.nvim/lua/neo-tree/utils.lua:833: attempt to index local 's' (a nil value)
stack traceback:
...eovimPackages/start/neo-tree.nvim/lua/neo-tree/utils.lua:833: in function 'brace_expand_split'
...eovimPackages/start/neo-tree.nvim/lua/neo-tree/utils.lua:951: in function 'brace_expand'
....nvim/lua/neo-tree/sources/filesystem/lib/fs_actions.lua:329: in function 'on_confirm'
...eovimPackages/start/dressing.nvim/lua/dressing/input.lua:108: in function ''
vim/_editor.lua: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```
> fix(fs): error when escaping out of `add` and `add_directory`

- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/components.lua
- lua/neo-tree/sources/filesystem/init.lua
- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
- lua/neo-tree/ui/renderer.lua
This PR implements open/closed states for empty folders which is required in order to complete [my other PR](https://github.com/nvim-neo-tree/neo-tree.nvim/pull/522).
This involved actively checking wheter newly revealed folder nodes are empty and if so, showing the "empty folder" icon directly. This led me to the idea to also check if the folder contains only a single child directory. By applying this check recursively, and scanning down the chain such directories, neo-tree will directly display all grouped directories if "group_empty_directories" is set. This recursive scanning will not recursively explode and scan exponentially many nodes, as it only scans what really needs to be shown in the tree. (See the GIF below).
[![neo-tree-demo.gif](https://s4.gifyu.com/images/neo-tree-demo.gif) …
> feat: New node-scanning algorithm and empty folder states

- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/commands.lua
Hi, first of all, thanks for this amazing plugin!
This is my first contribution and I kept the PR minimal because I want to first assess whether this feature is even wanted before diving deeper into the setup.
I propose to add a `same_level` boolean config option to control the behaviour on how created/pasted/moved files/directories get inserted into the tree:
The behaviour is only affected if the cursor during creation/pasting/moving is on a directory node. Currently, the items get inserted inside the directory under cursor. I personally find it more intuitive if they get inserted on the same level (i.e. "as siblings") to the directory under cursor, much like it behaves currently when the cursor is on a file.
If you think this feature is worth continuing to work on let me know. If no, …
> feat: add same_level config option

- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/ui/renderer.lua
fixes #714
the second commit is to avoid this from potentially happening in other edge cases
> fix: infinite recursion in empty folder with `hide_root_node` = true

- .github/workflows/ci.yml
- lua/neo-tree/events/queue.lua
- lua/neo-tree/setup/init.lua
- lua/neo-tree/sources/common/components.lua
- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
- lua/neo-tree/ui/renderer.lua
- lua/neo-tree/utils.lua
- tests/neo-tree/ui/icons_spec.lua
- tests/utils/fs.lua
> chore: update stylua

- lua/neo-tree/ui/renderer.lua
Hi! This PR fixes the issue in #740. I added a function to clean up the dummy neo-tree buffers the first time `renderer.show()` is called.
This is my first contribution to the project, so let me know if you have any comments 😅!
> fix: delete neo-tree buffers created by :mksession

- lua/neo-tree/events/init.lua
- lua/neo-tree/setup/init.lua
- lua/neo-tree/ui/renderer.lua
Further fix for #740. Added the cleanup step to be run every time a session is restored.
> fix(setup): subscribe neo-tree buffer cleanup to session load

- README.md
- doc/neo-tree.txt
- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/ui/renderer.lua
Implement #696:
- Added a command `close_all_subnodes` that behaves analogously to `close_node` but also collapses all nodes in the subtree. 
- Also changed `renderer.get_expanded_nodes()` to search for expanded subnodes of already collapsed nodes (this might make `close_all_nodes` slower, so I'm not sure if it should be changed or not)
> feat(command): add close_all_subnodes

- lua/neo-tree/sources/common/commands.lua
Fixes #646. I added some checks in `close_node` to prevent it from collapsing the root node (similarly to `close_all_nodes`).
> fix(command): do not collapse root node

- lua/neo-tree/sources/manager.lua
- lua/neo-tree/ui/renderer.lua
Fixes a flick issue in #767 by adding a validity check to make sure neo-tree does not close a valid neo-tree window on session restore.
> add neotree buffer valid check

- lua/neo-tree/defaults.lua
- lua/neo-tree/setup/init.lua
- lua/neo-tree/ui/renderer.lua
fixes #778
This moves the session cleanup functionality to an opt-in feature instead of enabling it automatically for everyone.
The new config option is:
```lua
auto_clean_after_session_restore = false, -- Automatically clean up broken neo-tree buffers saved in sessions
```
I also moved the first cleanup action from the renderer to the setup function.
> fix: do not auto clean up buffers after session restore, unless opted in

- lua/neo-tree/utils.lua
fixes #789. One comment is that if the width is invalid, normally neo-tree still works and doesn't throw an error. However, since I added this fix, errors only appear if you happen to open a file when there's no other windows (which only happens rarely). This is a bit inconsistent and might confuse users, should we bother at all?
> fix: error opening file when window.width is not lua number

- lua/neo-tree/sources/filesystem/init.lua
- lua/neo-tree/sources/filesystem/lib/filter.lua
- lua/neo-tree/sources/filesystem/lib/filter_external.lua
fixes #794
This fixes problems related to making corrections in fzy search mode. Previously, it only worked correctly going forward,
as in adding characters without making corrections. It now works consistently with corrections because:
- The files found using `fd`/`find` are no longer cached at all. Another way to fix this would be to track the search term and reset the cache when the term gets shorter. I don't think that is worth the complication though.
- I fixed a bug where going to an empty input would reset your search settings for the session, sending you back to the old fuzzy search mode.
> fix: handle backspacing correctly in fzy search

- lua/neo-tree/sources/buffers/init.lua
- lua/neo-tree/sources/buffers/lib/items.lua
- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/sources/common/file-items.lua
- lua/neo-tree/utils.lua
With this PR, unnamed buffers will always show in the buffers list. We also now properly support follow current file with new buffers and switching to a specific unnamed buffer.
> feat(buffers): show `[No Name]` buffers in buffers list

- lua/neo-tree/sources/filesystem/init.lua
- lua/neo-tree/sources/filesystem/lib/filter_external.lua
The advantage here is that the fzy search will work in much larger directories because we no longer try to load **all** of the files and fzy search in memory. Now we will have a first level search using the external program which searches for the existence of all of the characters in the term.
The downside is that it will no longer find matches that are in a different order than what you type. I think that is a reasonable trade off because the old way was only usable in small projects.
If we want to recreate a perfect fzy search, we should just use fzy itself. I think we may be able to use [nvim-fzf](https://github.com/vijaymarupudi/nvim-fzf) or at least lean from its code base.
The other change made here is that we now keep track of running jobs for the external find command and kill …
> feat(filesystem): use fd/find as first level filter in fzy, cancel jobs as needed

- README.md
- lua/neo-tree.lua
- lua/neo-tree/defaults.lua
- lua/neo-tree/utils.lua
closes #564, closes #802
default is set to not replace `{ "terminal", "trouble", "qf" }`
set `open_files_do_not_replace_filetypes = {}` to restore previous behavior.
> feat!: add config to prevent replacing specific filetypes

- lua/neo-tree/setup/init.lua
That message should have been logged at the `debug` level.
> feat: do not show "Window settings restored" message

- lua/neo-tree/git/utils.lua
> fix: handle errors in git utils convert_octal_to_utf8

- README.md
- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/filesystem/lib/filter.lua
related issue: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/451#issuecomment-1475284693
> feat: add fuzzy_finder_mappings to customize mappings for filter popup in fuzzy_finder_mode

- lua/neo-tree/utils.lua
Sometimes I get this error when I use Windows.
> fix: fix split command

- lua/neo-tree/defaults.lua
- lua/neo-tree/setup/init.lua
- lua/neo-tree/sources/buffers/init.lua
- lua/neo-tree/sources/buffers/lib/items.lua
- lua/neo-tree/sources/common/components.lua
- lua/neo-tree/sources/filesystem/init.lua
- lua/neo-tree/sources/git_status/init.lua
- lua/neo-tree/sources/manager.lua
- lua/neo-tree/utils.lua
Added highlight open file feature as described in #743. I'm not sure if there is any better way to cache this so that we do not have to loop over all buffers every time. Do you think adding to `state` is a good idea?
> feat: add highlight open files

- README.md
- doc/neo-tree.txt
- lua/neo-tree/defaults.lua
- lua/neo-tree/setup/init.lua
Added **global commands** feature. A user can specify a table with functions that will automatically be added to all sources. 
The table is `config.commands` and it's content is added to `config[source_name].commands` with `vim.tbl_extend`, and the "keep" option, to allow overriding the global implementation with a custom one in any source.
```lua
commands = {
hello = function()            -- define a global "hello world" function
print("Hello world")
end
},
window = {
mappings = {
["<C-c>"] = "hello"
-- define a global mapping to call 'hello' in every source
}
},
filesystem = {
commands = {
-- override implementation of the 'hello' action in filesystem source
hello = function()
print("Hello inside filesystem")
end
}
}
})
```
This means that pressing `CTRL-c` …
> feat: commands can be defined globally. fixes #707

- lua/neo-tree/setup/init.lua
Fixes #867
I've gone through the `neo-tree` source code and nowhere does it set `foldcolumn` so I'm honestly not sure when/where it's getting set to `0`, but this does resolve the issue perfectly. Let me know what you think!
> fix(setup): save and restore foldcolumn option

- .github/workflows/ci.yml
- lua/neo-tree/defaults.lua
- lua/neo-tree/setup/init.lua
- lua/neo-tree/sources/buffers/init.lua
- lua/neo-tree/sources/filesystem/init.lua
- lua/neo-tree/sources/git_status/init.lua
- lua/neo-tree/ui/selector.lua
This accomplishes 3 things
1) Resolves the issues initially reported in #873 (Source selector now reads names instead of module paths)  
2) Corrects potential error in `default_source` being nil (and tosses a warning to the user in the event that they do set it to nil)  
3) Adds a new attribute that sources can return called `display_name`. This is then interpreted into the source selectors "tab" name. If this attribute isn't provided, the source's name is used instead. These can still currently be overridden by the `config.source_selector.tab_labels`. I have also updated the internal sources to use this `display_name` instead of relying on the configuration to provide it for them.
> 873 source selector shenanigans

- doc/neo-tree.txt
- lua/neo-tree/defaults.lua
- lua/neo-tree/setup/deprecations.lua
- lua/neo-tree/setup/init.lua
- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/sources/document_symbols/init.lua
- lua/neo-tree/ui/selector.lua
RE: #479
Replaces `source_selector.tab_labels` with `source_selector.sources`.
Why? This allows users to have **much** more choice over the things that are displayed in their source selector. Previously, all sources in Neo-tree were added to the source selector and there was no way to remove any of them. This will get especially painful as Neo-tree grows and more developers write sources for it.
Additionally I added some logic to ensure that if `source_selector` is active, (IE one of the display bar options is enabled), that the first option in source selector is set to the `default_source` so that when users execute `:Neotree`, their source selector properly displays the first item in the sources.
Lastly, I fixed a few logs that had invalid function names in them, and updated the name of …
> Configurable source selector entries

- lua/neo-tree/ui/selector.lua
Fixes #848. 
The function `text_layout` doesn't work with the whole tab representation, which relies on `vim.fn.strdisplaywidth`. It seems that this function considers the tab representation string literally, and gives a length of more than 400 for just 3 tabs. The `text_layout` then truncates the tab representation, which results in weird values.
To fix this, I moved the `text_layout` logic to truncate `tab.text` instead.
> fix(source_selector): fix bug with tabs_layout

- README.md
- doc/neo-tree.txt
- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/document_symbols/commands.lua
- lua/neo-tree/sources/document_symbols/init.lua
- lua/neo-tree/sources/document_symbols/lib/symbols_utils.lua
Added functionalities to `document_symbols` to automatically focus on the symbol under the cursor. Turn this on by adding `document_symbols.follow_cursor = true`
> feat(document_symbols): added follow_cursor

- lua/neo-tree.lua
- lua/neo-tree/command/init.lua
- lua/neo-tree/setup/netrw.lua
Fixes #845 and #822
`:Neotree` and the default `hijack_netrw` behaviour would fail if `config.window.postion = current`. It seems that both `execute` in`command/init.lua` and `hijack` in `setup/netrw.lua` didn't set the correct winid in state when `config.window.position = current`. Changes to fix this are minimal and just involve getting the window position from the config.
This is my first PR to open source 🥳 and I'm quite new to neovim plugin development, any feedback would be appreciated.
> fix: set correct winid when window.position = current

- doc/neo-tree.txt
- lua/neo-tree.lua
- lua/neo-tree/setup/init.lua
- lua/neo-tree/sources/buffers/init.lua
- lua/neo-tree/sources/filesystem/init.lua
- lua/neo-tree/sources/manager.lua
- lua/neo-tree/ui/renderer.lua
- tests/neo-tree/sources/manager_spec.lua
I noticed that neo-tree cwd was sometimes getting out of sync with the real value. After some investigation I found that the manager uses `nvim_get_current_tabpage` to get the value stored in state (tabid but is called tabnr in code), but then uses the same value to get tab cwd using `vim.fn.getcwd` (which expects tab number). The values used in API and in vimscript functions are slightly different - tabnr is the visible position of a tab, while tabid refers to the tab object. 
To reproduce the bugs that I was expecting start Neovim, open two tabs, then set different tabcwd for one of the tabs and open neo-tree in both tabs. Then use `:tabmove +1` in the first (leftmost) tab - neo-tree will be out of sync with the actual tab cwd (as returned by `vim.fn.getcwd(-1, 0)`). You can also …
> fix: use correct conversion between tabid and tabnr when tracking cwd

- doc/neo-tree.txt
- feat(document_symbols): added follow_cursor(#880)
- fix: set correct winid when window.position = current (#874)
- fix: declare `bufnr` as local to avoid polluting global namespace (#883)
- fix!: use correct conversion between tabid and tabnr when tracking cwd (#842)
- Update doc
> Update doc, highlight and indent.

- lua/neo-tree.lua
closes: #828 Can not open file on first `<cr>` in lazy load.
[My comment](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/828#issuecomment-1529131383) explains the detail of this bug.
With this fix, when the setup function is called, neo-tree examines current buffer once to check if its a dir buffer or not.
Usually, this check is done in an autocmd [defined here](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/8d485aab32da9b8841d4af977f992b82b14af469/lua/neo-tree/setup/init.lua#L150) but this is too late in the case of lazy loading.
In order to make neo-tree work properly, we need to guarantee that the alternating buffer `"#"` must NOT be a _`dir buffer`_, and this hijack in setup function guarantees that even on lazy loading.
I am pinging people over on the issue thread. I …
> fix(hijack): Hijack on setup for lazy load

- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
This might be more of a workaround than a fix but in case of working with directories mounted from samba, `fs_open` seems to fail internally after file creation but before assigning file permission.
https://github.com/nvim-neo-tree/neo-tree.nvim/issues/911#issue-1692135414
I could not diagnose the core problem but it seems to fail regardless of neo-tree as shown in the following code which end up creating a file but with permission set to `r-xr-xr-w` (I guess it's more of a samba bug?).
So, to workaround this, I'd like neo-tree to not simply bail out when `fd` is nil [here](https://github.com/nvim-neo-tree/neo-tree.nvim/blob/8d485aab32da9b8841d4af977f992b82b14af469/lua/neo-tree/sources/filesystem/lib/fs_actions.lua#L367) but rather actually check the file existence and continue on when …
> feat(fs_actions): check file existence on fs_open error

- README.md
Hey, this is to fix the syntax issue in the config presented in the README file.
> fix the syntax issue in the config

- README.md
While #921 has mentioned about fixing about Nerd Fonts v3, it missed about source selector. This PR adds it.
> docs(readme): add Nerd Fonts v3 fix guide for source selector

- doc/neo-tree.txt
Fix typo in documentation.
Option name was wrong: `server_filter` -> `client_filters`
> fix(docs): typo in option document_symbols.client_filters

- lua/neo-tree/ui/renderer.lua
Save current window scroll offset using `vim.fn.winsaveview` when saving
current node position. Then, when restoring current node position,
restore saved window scroll offset using `vim.fn.winrestview`.
This fixes #781 
I also extracted one function to improve readability. I understand that this is a subjective assessment, so it is done as a separate commit and can be easily reverted if needed.
cc @miversen33
> fix: Prevent window from moving when reloading scrolled buffer

- lua/neo-tree/setup/init.lua
This fixes #870 
The root cause was that the fix from #628 was only taking into account unnamed buffers stripping from buffer name `[NoName]#` prefix to obtain the buffer nr. This caused to trim first 12 characters from the filename, which then caused `vim.cmd("b" .. bufnr)` to fail as the filename could not be found. 
There is still some flickering due to buffer being temporarily closed, but I don't think that it can be prevented. 
It is much more visible in the video than in real life (probably due to compression :thinking:)
[Kooha-2023-05-27-20-25-40.webm](https://github.com/nvim-neo-tree/neo-tree.nvim/assets/5662622/554645b9-4c10-48cb-b3ec-855ae9eb8286)
> fix: Prevent autocmd from failing when closing modified file

- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
To resolve issue https://github.com/nvim-neo-tree/neo-tree.nvim/issues/960, the PR wraps the code block with a pcall function, effectively preventing the error from being raised.
Windows user can use nvim even if the folder contains subfolders with higher permissions, for example in the HOME directory the Cookie folder did mess with this plugin.
**(PR has been opened twice because rebase was necessary)**
> Fix #960 wrap in `pcall` failing `closedir` call (REBASED)

- lua/neo-tree/ui/renderer.lua
this is a follow up to #953, which was a fix for #781
This fixes the problem where if you open `:Neotree current` in a window that has a terminal that has a lot of lines, then the tree will be scrolled down as far as it can go. I didn't really trace the execution, I just moved the save and restore of the window top line within the same conditionals as the saving of the currently focused node. It make sense that whatever situation would prevent a save/restore of the current node would also apply to the window scroll position.
FYI: @ghostbuster91
> fix: do not restore bad state for top line when opening neotree

- lua/neo-tree/sources/document_symbols/components.lua
Fix the bug when `add_blank_line_at_top = true` as mentioned in #879.
> fix(document_symbols): add_blank_line_at_top

- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
Ironing out some quirks with `create_node()` when using Neovim in Windows 11:
1. Added an extra prompt + check to allow users to use either `/` or their native `path_separator` if they are different.
2. When creating nested directories, the command silently fails when using `/`, but works as intended when using `\`. Example in the demo video below. Might be a libuv issue? Seems like it can be worked around by sanitizing with `windowize_path`.
https://github.com/nvim-neo-tree/neo-tree.nvim/assets/43484729/6b556928-8eec-43b7-a2f1-367523e3851d
> feat(fs_actions): Add support for non-`/` path separator in `fs_actions.create_node`

- lua/neo-tree/sources/common/components.lua
- lua/neo-tree/ui/renderer.lua
Indentation is broken when parent `indent_marker` is not shown in the node since it is the last element in the tree.
This happens only and only if value is exactly 1. See the indent of `./src/B/{a,b}.js`.
- `= 0`
- `= 1`
- `= 2` (`>= 2` all works)
When the indent is set to 1, the indent should only show `indent_marker` (or `last_indent_marker`) so that the indent width will be 1.
- `= 1`
---
Closes https://github.com/nvim-neo-tree/neo-tree.nvim/issues/924
https://github.com/nvim-neo-tree/neo-tree.nvim/pull/864#issuecomment-1578027693
https://github.com/nvim-neo-tree/neo-tree.nvim/pull/864#issuecomment-1579093376
> fix(renderer): no_next_padding to fix indentation set to 1

- lua/neo-tree/git/ignored.lua
- lua/neo-tree/ui/renderer.lua
closes #929
`show_anyways` is only used in this context (there is no other reference to `show_anyways` other than my fix), so deleted in line 200.
> feat(ui): hide hidden files irrespective of `hide_gitignored` option

- lua/neo-tree/sources/common/components.lua
Closes #774.
The old code goes wrong at line 106 when `defined = { other_keys = "foo" }` since it does not set `texthl` key although it is required to pass the if-check at line 114.
This PR changed the algorithm to specifically set `texthl` when not found.
Same for `text` in `texthl`.
> fix(diagnostics): fix diagnostics component mechanism

- lua/neo-tree/sources/filesystem/init.lua
- lua/neo-tree/utils.lua
Closes #948.
`M.navigate` calls debounce and therefore is async. So `utils.open_file` finishes before it resulting to neo-tree opening itself again after closing with event handler.
Passing `utils.open_file` as a callback solves the problem.
I've also updated type notation of `utils.open_file` since parameter `open_cmd` can be `nil`.
> fix(fuzzy): delay `open_file` after search to navigate first

- lua/neo-tree/command/init.lua
This fixes #985
When a root path was supplied as an argument to the Neotree command or to execute on Windows, the necessary separator was removed. ":Neotree C:\", for instance, would become "C:" and this resulted in an empty listing.
Instead of testing if the length of args.dir is greater than 1, this now compares it to 3 on Windows while remaining 1 on other operating systems, including WSL.
```lua
-- Root paths on Windows have 3 characters ("C:\")
local root_len = vim.fn.has("win32") == 1 and 3 or 1
if #args.dir > root_len and args.dir:sub(-1) == utils.path_separator then
args.dir = args.dir:sub(1, -2)
end
```
I added a comment as well just to clarify what was going on. Though, maybe it'd be better to have a constant. In utils, there's an is_windows variable set (which includes WSL). …
> fix: Preventing removal of necessary root separator on Windows

- lua/neo-tree/utils.lua
Fix an issue in buffer view, where a blank buffer would open instead of the selected buffer when using the `open_split` shortcut.
More details on #898
> fix: split from buffer view opens blank buffer (#898)

- lua/neo-tree/ui/renderer.lua
fixes #1000
Alternate solution to #1007 proposed by @pysan3.
The problem was that we were creating a new NuiTree instance and attaching it to an existing buffer that already had a tree rendered in it. The solution here is to identify when the tree exists and the buffer it manages is still good, and in that case just reuse that tree instead of creating a new one.
Along the way I also made it so that a sidebar will reuse an existing buffer rather than creating a new one every time the window opens. This should just be a tiny bit more efficient and will help on another thing we are working on: reusing sidebar windows across sources instead of having to close them every time.
> fix: reuse NuiTree and buffer if possible, fixes ghost tree problem

- lua/neo-tree/utils.lua
Following up on the conversation in #752, the goal is to prevent the flickering caused by the closing and reopening of the `Neotree` window when we change the source. Here are my current thoughts:
- Add a table to `manager` to keep track of the states by position. Whenever the source is created, the manager will use the old (if exists) window. This avoids the flickering window and also allow window-specific settings such as width (in #928)
- I am also thinking about the idea of having multiple state at the same time, instead of just one. This allows more flexible layouts, for example, `filesystem` on the left, `document_symbol` on the right, and `diagnostics` at the bottom. This might, however, come with some complexity especially when two of the same source coexist (e.g. the user uses …
> [WIP] feat(manager): allow window-specific state 

- lua/neo-tree/command/init.lua
- lua/neo-tree/ui/renderer.lua
- lua/neo-tree/ui/windows.lua
fixes #713
This adds logic to reuse Neotree windows between sources instead of always closing the window when opening a new source. It also improves upon the concept of reusing the buffer when possible instead of recreating it from scratch each time. These are primarily optimizations for quickly switching between sources when they are shown as sidebars.
> fix: reuse windows and buffers when possible, prevents flashing when switching

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- Greatly inspired by: https://github.com/folke/noice.nvim/tree/main/.github/ISSUE_TEMPLATE
Came from the discussion https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/1006.
@miversen33 @cseickel @nhat-vo
> feat(issue): add `bug_report`, `feature_request` issue template

- README.md
- lua/neo-tree/defaults.lua
- lua/neo-tree/setup/deprecations.lua
- lua/neo-tree/sources/buffers/init.lua
- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/sources/filesystem/init.lua
- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
- lua/neo-tree/utils.lua
- tests/neo-tree/command/command_spec.lua
- tests/neo-tree/sources/filesystem/filesystem_command_spec.lua
https://github.com/nvim-neo-tree/neo-tree.nvim/issues/999#issuecomment-1601887559
Closes: #999
Related: #903
- `filesystem.follow_current_file` -> `filesystem.follow_current_file.enabled`
- Added in `deprecations.lua`
- `filesystem.follow_current_file.leave_dirs_open` defaults to `false`, which does not change the default behavior.
- Although `:Neotree reveal` automatically opens dirs to focus the current file, `filesystem.follow_current_file.enabled == false` && `:Neotree reveal` => does not respect `leave_dirs_open` nor remember dirs opened by `reveal`. This option only works when `enabled == true` is explicitly set.
- Changed `buffers.follow_current_file.enabled` as well for compatibility, but `buffers.follow_current_file.leave_dirs_open` is never referenced since in buffers source, …
> feat(sources): add follow_current_file.leave_dirs_open option

- doc/neo-tree.txt
README has the correct info, but the help file is not up to date.
For reference, the README with accurate info and the relevant code:
- https://github.com/nvim-neo-tree/neo-tree.nvim/blob/ee0c058f3fa36675c8fb93cb44b94ed678db6cfa/README.md?plain=1#L109-L119
- https://github.com/nvim-neo-tree/neo-tree.nvim/blob/ee0c058f3fa36675c8fb93cb44b94ed678db6cfa/lua/neo-tree/sources/common/components.lua#L89-L100
> docs: fix outdated diagnostics signs info

- README.md
I recently reconfigured my terminal and editor, so I'm using v3 nerd fonts. Using the winbar source selector, I noticed icons were broken, so I applied the config suggested in the readme. I realized that the buffers entry was missing, so I determined that the existing code point was 0xf719, `nf-mdi-file_document_box`:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/7f6fa04dbd8e8c79d1af33bc90e856b65d8641da/lua/neo-tree/sources/buffers/init.lua#L14
The equivalent glyph in v3 has a different name, `nf-md-text_box`, and is at 0xf021a.
This PR adds a line to the readme config example to fix the buffer icon for V3 nerd fonts.
> docs: add Buffers entry to Nerd Fonts v3  source selector example

- lua/neo-tree/git/ignored.lua
- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/sources/common/node_expander.lua
- lua/neo-tree/sources/filesystem/commands.lua
- lua/neo-tree/sources/filesystem/init.lua
- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
- lua/neo-tree/ui/renderer.lua
This relates to #701 
This is not a full fix for the builtin `expand_all_nodes` method but rather a fix that enables fixing it. It also enables fixing function from wiki to recursively expand nodes under the cursor (more important in my opinion).
List of changes broken down by commit:
1. Add callback to `toggle_directory` - this is the most important. Luckily it is not a breaking change because callback was previously `nil` anyway. 
Justification:
`fs.toggle_directory` calls `fs_scan.get_items` that calls `sync_scan` that for the 
`scan_mode=="shallow"` calls `sync_scan` and then `job_complete`. 
Here is where the problem starts - `job_complete` checks if `git_status_async` is set and 
if so it registers a callback in `git.mark_ignored` method. That callback is important 
because it …
> refactor(filesystem): fix recursive expand of nodes

- lua/neo-tree/sources/common/components.lua
Closes: #1034
`require'nvim-web-devicons'.get_icon(filename, extension, options)` has the ability to guess the file extension on its own and does not require the `extension` argument.
This PR simply deletes that argument, and passes everything to them to decide the icon.
Docs: https://github.com/nvim-tree/nvim-web-devicons#get-icon
(The browser might not be able to display the icons tho...)
```txt
require("nvim-web-devicons").get_icon("something.spec.ts")  DevIconSpecTs
require("nvim-web-devicons").get_icon("hoge.PNG")  DevIconPng
require("nvim-web-devicons").get_icon("hoge.png")  DevIconPng
require("nvim-web-devicons").get_icon(".zshrc")  DevIconZshrc
require("nvim-web-devicons").get_icon("hoge.zsh")  DevIconZsh
require("nvim-web-devicons").get_icon(".bashrc")  DevIconBashrc …
```
> fix(devicons): let `nvim-web-devicons` decide the extension

- lua/neo-tree/utils.lua
Related
- #898 
- #989 
- #1004 
- #1005 (Introduced here)
> fix(utils): typo in open split command

- README.md
- lua/neo-tree/defaults.lua
- lua/neo-tree/ui/inputs.lua
This PR addresses the issue discussed in [#1039](https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/1039), where users were unable to switch to normal mode in the NeoTree rename popup by pressing the escape key.
**Benefits:**
This change significantly improves the user experience by allowing users to switch to normal mode without closing the popup, and provides a way to close the popup from normal mode.
Moreover, it offers additional benefits when dealing with long file names. Users can now leverage normal mode commands such as `dw` (delete word), `dt`. (delete until dot), or `dd` (delete line) to edit file names more efficiently. This makes the renaming process faster and more intuitive, especially for those who are accustomed to Vim's normal mode operations.
Please let me know …
> feat(ui/inputs): enable normal mode in rename popup

- lua/neo-tree/command/parser.lua
Pretty simple fix but appears to resolve this. Tagging @emilgedda for testing and @cseickel / @pysan3  for review :)
> fix: normalize file paths (#993)

- README.md
- lua/neo-tree/defaults.lua
- lua/neo-tree/setup/deprecations.lua
- lua/neo-tree/ui/popups.lua
- lua/neo-tree/ui/renderer.lua
closes #1028
In the end there is no change with the default options, but now it is controlled by a mapping which the user can set to any key that they want.
> refactor!: remove `close_floats_on_esc_key` opt, replace with `cancel` mapping

- lua/neo-tree/ui/windows.lua
fixes #1053
This fixes a bug introduced in #1011 which incorrectly makes trees in new tabs try to reuse windows from other tabs.
Now there is a collection of windows **per tab** that may be reused.
> fix: restore ability to have separate trees for each tab

- README.md
Lazy uses `dependencies` instead of `requires` 😄
Source: [Lazy.nvim migration guide](https://github.com/folke/lazy.nvim#packernvim)
> docs: Fix lazy.nvim instructions

- lua/neo-tree/sources/common/preview.lua
There is a check in place which prevents closing the preview if the user jumps into the preview window. This makes sense if the preview is floating, but causes problems otherwise by not properly reverting the preview, for example when closing the neo-tree source.
This should be fixed simply by also checking if the preview window is floating.
> fix(preview): revert when jumping to preview window if it is not floating

- lua/neo-tree/utils.lua
Closes #1076
@miversen33 Could you please take a look at this fix? It's a subsequent fix of the Windows path adaption since PR #1023.
I've tested on my side for these test cases and all of them have passed:
- `d:\test path\test.txt`
- `d:\test\nested dir\test.txt`
- `d:\test\(inner)\test.txt` _<-- regression test for #1023_
- `d:\test\ leading\test.txt`
- `d:\test\trailing \test.txt`
> fix: Leading slashes of spaces in paths on Windows when opening files

- lua/neo-tree.lua
- lua/neo-tree/defaults.lua
> fix: restore deprecated `close_all` command, but remove from docs

- lua/neo-tree/sources/filesystem/init.lua
- lua/neo-tree/sources/manager.lua
BREAKING CHANGE: deprecated `neo-tree.sources.manager.reveal_current_file()` and `...reveal_in_split()`, removed `neo-tree.reveal_current_file`
Since `neo-tree.reveal_current_file` has actually been broken since 3.0 was released and should bhave been removed in 2.0, I don't so much harm in just deleting it now. These were all leftovers from the old `NeoTree*` commands.
see #1098 for more info
> fix!: fix and deprecate old `reveal_current_file` methods

- lua/neo-tree/defaults.lua
- tests/neo-tree/ui/icons_spec.lua
The original icon was chosen before we had the feature to distingiush between an empty folder and an empty folder that was "open". It was intentionally different as as not to lead to confusion, it was meant to indicate that the folder was neither open nor closed, just empty.
Now that we do actually track the open state of a closed folder and there are some situations where the behavior is different based on whether an empty folder is open or closed, it's important to show which state it is in.
The new icons I hope make it obvious that the folder is empty while still displaying separate open and closed states.
> feat: improve default empty folder icons

- lua/neo-tree/ui/renderer.lua
This is to fix errors like this:
```
[Neo-tree ERROR] Error in event handler for event vim_diagnostic_changed[filesystem.vim_diagnostic_changed]: ...r/.local/share/nvim/lazy/nui.nvim/lua/nui/utils/init.lua:130: Invalid buffer id: 42
```
They mostly happen when quickly open and closing the tree, such as with position=current. They are not really a problem but the error messaage is a nuisance. This change just ignores the errors.
> fix: ignore errors from failed redraw due to window being closed

- lua/neo-tree/sources/common/components.lua
This fixes the case where a file may have been deleted but there is still an open buffer, which would show errors in the buffer list if it was open in a window large enough to show those columns. Now it is handled gracefully when a buffer is not (or no longer) actually a file in the filesystem.
> fix: handle missing stats gracefully in file detail columns

- README.md
- lua/neo-tree/defaults.lua
Currently the only ways to enable the `symlink_target` component is copying the entire the directory and file renderer configs or defining a custom config that includes them. This can be annoying to maintain if the default rendered configuration changes.
This PR uncomments the component in the default config and disables it by default as mentioned in [this comment](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/746#issuecomment-1429090271).
> refactor!: setup the `symlink_target` component using default config

- lua/neo-tree/ui/renderer.lua
- lua/neo-tree/utils/init.lua
This tweaks how file stats are pulled so that sources (internal or external) can provide their own. This is only necessary if the node does not represent an object in the local filesystem.
See here for an example the API to fulfill:
https://github.com/nvim-neo-tree/example-source/blob/1be4d91d94875501cb4db1a61aa5155b6cd654bc/lua/example/init.lua#L19-L49
> feat: setup hooks for sources to provide custom `stat`s for nodes

- README.md
- lua/neo-tree/command/init.lua
- lua/neo-tree/command/parser.lua
- lua/neo-tree/defaults.lua
- lua/neo-tree/setup/init.lua
Implement #775 , add a source option `last` to allow users to open the last source used.
> feat(command): add source `last` refers to the last executed source

- lua/neo-tree/defaults.lua
- lua/neo-tree/git/ignored.lua
- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
fixes #1125, fixes #997
The problem was actually cuased by calling out to git too many times when checking the git ignored status of files. This only happens when there are many folders being shown at once. The solution was to limit the number of concurrent running jobs to 50.
I also snuck in a config option to completely disable checking gitignore when searching, as this has a big performance impact on the "search as you type" mode. Personally, I'd rather it be fast than be able to mark gitignored items.
```
filesystem = {
check_gitignore_in_search = false, -- Check gitignore status for files/directories when searching.
-- Setting this to false will speed up searches, but gitignored
-- items won't be marked if they are visible.
}
})
```
The default value is …
> fix: prevent "too many open files" errors from git ignored check

- lua/neo-tree/ui/renderer.lua
fixes #1046
I have not actually been able to recreate the issue, but I can see how it might happen and these changes will prevent errors due to looking up buffer local variable for a buffer that may no longer exist.
> fix: improve safety of `window_exists` function

- lua/neo-tree/utils/init.lua
If you disable a diagnostic with `vim.diagnostic.disable`, don't count towards the diagnostic count.
> Ignore disabled diagnostics

- lua/neo-tree.lua
After moving utils.lua to utils/init.lua the paste_default_config function fails to locate its source root.
> feat: Fix paste_default_config

- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/buffers/lib/items.lua
- lua/neo-tree/sources/common/components.lua
This adds an option, which is disabled by default, to sort terminals at the top of the buffers list instead of the bottom. It also fixes the ternminal icon.
The new option is:
```lua
buffers = {
terminals_first = false
}
})
```
> feat(buffers): add `terminals_first` option

- doc/neo-tree.txt
Sort by **n**ame should be `on`, i guess.
> doc: typo fix (duplicated `om`)

- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
fixes #1174
When a file is deleted from neo-tree, neo-tree checks to see if it is open anywhere. If it is, neo-tree will replace this buffer with the "alternate" buffer before wiping out that buffer.
As detailed in #1174, if this is done from a floating window, this can lead to neo-tree itself becoming the replacement which then takes focus unexpectedly which can then lead to all sorts of shenanigans and bad results.
The solution is to make sure that the replacement file is a real file and not a special buffer type. This includes neo-tree which makes it a direct fix for this specific problem, but it also includes other plugin buffers and special buffers like quickfix and help. If there is no valid buffer to replace the deleted file with, then a new buffer will be created to as a …
> fix(filesystem): ensure replacemnt for deleted buffer is a real file

- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
fixes #1152
With this change, the gitignored status will always be loaded unless:
- `filtered_items.hide_gitignored` is false AND `enabled_git_status` is false
- you are doing a search and `check_gitignore_in_search` is false
- there are no items to show
Note that this does not affect dotfiles, which will show as normal files when `filtered_items.hide_dotfiles` is false.
> fix(filesystem): always show gitignored status unless `enable_git_status` is false

- doc/neo-tree.txt
- lua/neo-tree/ui/renderer.lua
With this feature, you can add labels for custom mappings (lua functions).
```lua
["<c-f>"] = {
function(state)
require("telescope.builtin").live_grep({ cwd = context_dir(state) })
end,
config = { text = "live grep" }, -- text here
},
```
Before
After
> feat: custom text for mappings in help window

- doc/neo-tree.txt
- lua/neo-tree/ui/renderer.lua
This aligns the mapping API closer with the core `keymap.set` lua API in Neovim
This is a continuation on #1186
> feat!: rename `label` to `desc` for mapping descriptions

- lua/neo-tree/ui/inputs.lua
Closes: #1172
A very simple PR; inserts a `'\n'` between the popup message and default value instead of a space.
> feat(input): add newline when `use_popups_for_input = false`

- lua/neo-tree/sources/common/commands.lua
This purpose of this change is to keep `state.explicitly_opened_directories` up to date not only when you open Nodes, but also when you close them. 
Specifically, this applies to actions `close_all_nodes` and `close_all_subnodes`.
Not sure if this change is fixing some bugs in the neo-tree itself. The reason why I need this: one of my plugins uses `state.explicitly_opened_directories` to save and restore Neo-tree when switching projects, and in above cases, 'explicitly_opened_directories' variable does not correspond to the real state. This change will fix [the bug.](https://github.com/coffebar/neovim-project/issues/12)
> Update state.explicitly_opened_directories when collapsing by action close_all

- lua/neo-tree/ui/renderer.lua
This contains a small fix to make it so that the return value of key mapping callbacks get passed on to nvim.  This is needed so key mappings with the `expr=true` option work.   See issue #1192 for details.
Fixes #1192
> Return key mapping callback return value, so eval option works

- README.md
- doc/neo-tree.txt
- lua/neo-tree/command/init.lua
- lua/neo-tree/command/parser.lua
- lua/neo-tree/ui/selector.lua
Closes: #1170, #895
Add command option `:Neotree selector=true / false` to toggle source selector on command.
Note: @cseickel 
This adds a new field `state.enable_source_selector` which I'm not sure if you are a fan of.
If you don't want to introduce a new field to `state`, I believe it would be pretty much impossible to implement this feature tho.
If you are OK with this PR, I'll add some documentation and change this from _draft_ to a PR.
> feat(selector): add command option to toggle source selector

- lua/neo-tree/sources/buffers/init.lua
- lua/neo-tree/sources/document_symbols/init.lua
- lua/neo-tree/sources/git_status/init.lua
- tests/neo-tree/sources/navigate_spec.lua
Closes #1151.
As @cseickel mentioned in [this comment](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1151#issuecomment-1773838523), we should have the same number of arguments for all `M.navigate` functions found in the sources.
I've also added a `busted` test to ensure that all of the sources have the same number of args.
This was **before** I made the [last commit](https://github.com/pysan3/neo-tree.nvim/pull/1/commits/bda666ffe7ce248ad9b3754c4b699fa78b47d09e).
https://github.com/pysan3/neo-tree.nvim/actions/runs/6604075269/job/17937819320
After the last commit.
https://github.com/pysan3/neo-tree.nvim/actions/runs/6604154767/job/17937988093
> feat(sources): fix and test all `source.navigate` to have same nparams

- lua/neo-tree/ui/inputs.lua
NOTE: I really don't know why but letters before the first '\n' is not rendered execpt in `noice.nvim` when `vim.opt.cmdheight = 0` <2023-10-24, pysan3>
If you know any other solution to this problem, I am more than happy to revert this issue.
> fix(ui): workaround #1197

- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
fixes #1179, fixes #911
Up until now we were calling the function with the wrong args. Mode was being passed in the argument that should have been permissions, which resulted in a value of 577 being set. Somehow this worked out and a subsequent call to change the permissions to 420 succeeded, so very few people noticed the error.
> fix(filesystem): use correct flags and permissions when creating file

- lua/neo-tree/events/init.lua
When verbose mode is used (`nvim -V1` or `:verbose ...`),
`vim.fn.expand('<afile>')` throws an error upon any WinEnter autocmds.
To avoid such errors, we can protect the call and suppress any E495
errors. See #1145 for more details and analysis.
Fixes #1145.
> fix: prevent expand(<afile>) from raising errors when verbose is set

- README.md
- doc/neo-tree.txt
- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/preview.lua
Closes #1196
Tagging some people that might be relevant. (Please ignore if you are not interested)
@SlimShadyIAm @cseickel
> feat(preview): use image.nvim to load images into preview window

- lua/neo-tree/ui/renderer.lua
This also adds the `desc` when using a function by name
> Fix `desc` being filtered out of mappings

- README.md
Fixing a typo in the readme,`:Neo-tree` doesn't work as a command, it should be `:Neotree`
> docs: use `:Neotree` instead of `:Neo-tree` for nvim command

- lua/neo-tree/sources/common/help.lua
When the list of keymaps is too long, the borders of the popup help window are not displayed properly.
Before
After
> fix: set max height for popup help window

- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/commands.lua
This feature was asked here: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1165#issuecomment-1797935289
Basically to add a keybind to open the top level file of nested files without expanding it.
Could you review this as well? @@Teddytrombone 
---
I mean to have one command that does the following:
1. when run on a closed folder/directory -> expands it
2. when run on a file with other files nested under it -> opens the file without expanding it
3. when run on any other file -> opens the file
Number 2 is not possible right now as far as I know, because the built-in open command will always first expand files with nesting and then open it when you run it again on the same file.
_Originally posted by @kmoschcau in https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1165#issuecomment …
> feat(commands): add option to open top file even when nested

- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/commands.lua
RETRY OF https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1219
- use `{ "open", config = { expand_nested_files = true } }` for old behavior
- `no_expand_file` options is deprecated, move to `expand_nested_files` (OPPOSITE)
I'm not really sure what is going on.
I'm so sorry to spam you with notifications...
> fix(commands)!: open nested files default to open instead of expand

- lua/neo-tree/sources/common/file-nesting.lua
- Extension mode: add an additional check for the basename. Fixes #1216 
- Pattern mode: if ignore_case is enabled, also make globs for nested files cas insensisitve, not only the pattern. Fixes #1217
> fix(file_nesting): fixes and improvements for all file_nesting modes

- lua/neo-tree/git/status.lua
- lua/neo-tree/sources/filesystem/init.lua
- lua/neo-tree/utils/init.lua
closes: #1214
Please read [my comments](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1214#issuecomment-1807104855) for the explanation.
But ultimately, this is a failure of an untyped scripting language lol.
We definitely need to introduce type notations at some point. I'm too sick of these kind of errors.
> fix(filesystem): fixed call to debounce with wrong arguments

- lua/neo-tree/sources/filesystem/commands.lua
- lua/neo-tree/sources/filesystem/init.lua
Requested [here](https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1214#issuecomment-1807130056), this PR changes the cursor position to the newly created file after `copy` command instead of focusing the src file.
https://github.com/nvim-neo-tree/neo-tree.nvim/assets/41065736/47daf22d-2e66-45e4-bce5-ccf5464b32cf
> feat(filesystem): move to new dst after copy / move in filesystem

- lua/neo-tree/setup/init.lua
- lua/neo-tree/utils/init.lua
- tests/neo-tree/sources/filesystem/filesystem_netrw_hijack_spec.lua
fixes #1225, fixes issues form discussion #1234
Somehow the buffer_changed event was not connected to an autocmd, it was probably lost along the way. 
I also discovered that the diagnostics was no longer setting the most severe as the final level. This was also something that was broken recently.
Finally, I think I fixed the glitchy test issue from #1225. It had an extra test that was not related to what should have been tested. I'm not sure why it sometimes worked...
> fix: fix buffer_changed event, fix diagnostics final severity

- lua/neo-tree/utils/init.lua
Fixes #1256 . One thing to note, NeoVim normalizes paths differently on Windows than a lot of plugins do, so I did this in a way that keeps it consistent with Neo-tree's code, which is to use backslashes on Windows.
> fix(filesystem): Mixed path separators in Windows

- lua/neo-tree/sources/common/components.lua
After https://github.com/neovim/neovim/pull/26193 , the internal implementation of the diagnostic signs changed to the new extmark-based sign, `sign_getdefine` will no longer work.
> fix: compatibility with 0.10 extmark sign

- lua/neo-tree/ui/renderer.lua
When opening files you had to scroll down to find, the neo-tree window jumped to the top (see #1025).
This is because Neovim changed the way `nvim_buf_set_lines` works in https://github.com/neovim/neovim/commit/008154954791001efcc46c28146e21403f3a698b (https://github.com/neovim/neovim/pull/24824) and later in https://github.com/neovim/neovim/pull/24889
This change in Neovim caused some problems in plugins:
- https://github.com/nvim-telescope/telescope.nvim/issues/2667
- https://github.com/folke/which-key.nvim/pull/516
To ensure the window stays fixed, we have to use `winsaveview` and `winrestview` (wrapped in `M.position`) inside `render_tree`.
Fixes #1025 
Fixes #996
> fix(renderer): fix jumping to the top when opening files.

- doc/neo-tree.txt
For my system the symbols-table needs to be within a git_status-table. 
My system has the versions below installed:
"lazy.nvim": { "branch": "main", "commit": "96584866b9c5e998cbae300594d0ccfd0c464627" } 
"neo-tree.nvim": { "branch": "v3.x", "commit": "77d9f484b88fd380386b46ed9206e5374d69d9d8" }
> doc: correct table for git symbols to be within git_status table

- lua/neo-tree/ui/renderer.lua
Sorry for the bug. This should fix it.
Do you prefer to have the code without the comment?
Fixes #1279
> fix(renderer): after focusing a node, such node was always focused

- lua/neo-tree/defaults.lua
> chore: move popup_border_style description to above the key

- Dockerfile
`make test-docker` was failing for me.
I fixed it by adding nvim-web-devicons. Not sure if it was necessary.
> chore(dockerfile): add nvim-web-devicons

- lua/neo-tree/sources/common/components.lua
> fix(diagnostic): `text` is `nil`

- lua/neo-tree/ui/inputs.lua
It is kind of cumbersome to input "y or n", and press <kbd>enter</kbd> for the confirm process, why not just press <kbd>y</kbd> or <kbd>n</kbd> instead.
> fix(prompt): confirm `cwd` changing using `vim.fn.comfirm`

- lua/neo-tree/sources/filesystem/init.lua
`\` and `/` both appears in the path, lead to string comparision problem on windows platform, user can not focus on the buffer file.
> fix(filesystem): fix filesystem path on windows platform

- lua/neo-tree/setup/init.lua
This is an incredibly boring PR. It adds a space to the `b[uffer]` command so that buffer names that use absolute Windows paths can be used without causing errors. This is in line with usage described in [`:h :buffer`](https://neovim.io/doc/user/windows.html#%3Ab) and [`:h {bufname}`](https://neovim.io/doc/user/windows.html#%7Bbufname%7D).
I've manually tested this change on Windows and WSL with the following types of buffers to ensure no regressions as best I can:
- No name buffers
- Buffer names with no spaces
- Buffer names with spaces in the path but not filename
- Buffer names with spaces in the filename but not path
- Buffer names with spaces in both path and filename
All cases result in the correct behavior: a warning is issued and the unsaved buffer is focused, without causing …
> fix: make buffer command compatible with Windows paths (#1350)

- lua/neo-tree/sources/common/components.lua
- lua/neo-tree/sources/manager.lua
- lua/neo-tree/utils/init.lua
This PR changes the handling of paths on Windows systems to address a few open issues. This builds on the work originally introduced in #1023 (to address #889). Realistically, this is another attempt to deal with a (neo)vim issue as mentioned in https://github.com/neovim/neovim/issues/3912 (no real update since 2015).
I've added some doc comments to help with maintainability, but if it's too verbose I'm happy to edit.
I've run tests locally and all pass, but I would really love to add regression tests for path escaping so we don't run into more problems in the future. However, I'm having trouble figuring out how to deal with platform-specific behavior of `vim.fn.fnameescape` (e.g., if you run tests on WSL or macOS, you won't get Windows path escaping). If anyone has any ideas for adding …
> fix: improve path escaping for commands on Windows

- lua/neo-tree/sources/filesystem/init.lua
- lua/neo-tree/sources/manager.lua
- lua/neo-tree/ui/renderer.lua
We need to be more careful when to save and restore the cursor position as we cannot overwrite the position anymore with https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1288.
closes #1310
Please read the LONG discussion from https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1354#issuecomment-1946307225 as it describes the issue and the reason thoroughly.
I will keep this as draft until I get some people to test this code as I might have missed some more edge cases.
Would you mind testing this code? @georgeguimaraes @mehalter @XavierChanth
```lua
{ 
"pysan3/neo-tree.nvim",
branch = "update-curpos-before-expand",
version = false,
```
> fix(renderer): clean out edge cases of cursor.position.restore

- lua/neo-tree/sources/filesystem/init.lua
- lua/neo-tree/utils/init.lua
This PR fixes a quite niche Windows bug where quickly changing popup windows could cause Neo-tree to try and follow (and thus normalize) an `nil` file path. This causes an error message to be printed, despite not actually being an issue for Neo-tree.
Essentially the problem is:
- Some form of popup window (like `NuiInput`) closes, changing the active buffer
- This causes the "follow" event to be fired from Neo-tree, but it is debounced: https://github.com/nvim-neo-tree/neo-tree.nvim/blob/7d3b02073e59ed9ef271795787de76d0de8f5294/lua/neo-tree/sources/filesystem/init.lua#L105
- A `toggleterm` floating window is opened (triggered from the previous `NuiInput` by `on_submit`) and changes the active buffer to be a `term://` path before the debounce timer finishes
- The `follow_internal` function …
> fix: skip normalizing empty file paths

- lua/neo-tree/ui/renderer.lua
Originated from: https://github.com/nvim-neo-tree/neo-tree.nvim/discussions/1374
I reported this before, but it's not completely fixed: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/996
I tracked it down to this piece of codes:
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/459c60317cc1d251f6eb3b6f010d015d5d24b806/lua/neo-tree/ui/renderer.lua#L542-L547
If I comment it out, everything works perfectly as expected.
Anybody knows what that piece of code does?
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/459c60317cc1d251f6eb3b6f010d015d5d24b806/lua/neo-tree/ui/renderer.lua#L542
This moves the current node at the bottom of screen.
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/459c60317cc1d251f6eb3b6f010d015d5d24b806/lua/neo-tree/ui/renderer.lua#L546
Then this moves …
> fix(renderer): fix cursor jumping

- doc/neo-tree.txt
- lua/neo-tree/events/init.lua
- lua/neo-tree/setup/deprecations.lua
- lua/neo-tree/ui/inputs.lua
We already have an option to default to normal mode in nui inputs.
`config.enable_normal_mode_for_inputs`
However, it looks like users want more power of customization to the details. (https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1371)
So why not just let users do whatever they want with absolute power?
All `function/string/table` are considered true-thy so this will cover backwards compatibility.
> feat(nui): allow callbacks in nui input with option

- lua/neo-tree/utils/init.lua
This PR addresses more edge cases with path escaping and vim commands, as noted in #1382.
After some testing, I found that only a small number of punctuation characters required the extra escape after  `vim.fn.fnameescape`. They are: `&`, `(`, `)`, `;`, `^`, and `` ` ``.
<details>
<summary>Details</summary>
Testing method used was running `:luafile %` with the following `test.lua` on a Windows machine:
```lua
-- copy/paste from neo-tree
local is_windows = vim.fn.has("win32") == 1 or vim.fn.has("win32unix") == 1
local escape_path_for_cmd = function(path)
local escaped_path = vim.fn.fnameescape(path)
if is_windows then
for _, c in ipairs({ --[[ add characters as cases fail ]] }) do
escaped_path = escaped_path:gsub("\\%" .. c, "\\%1")
end
end
return escaped_path
end
-- end copy/paste …
```
> fix: continue improving Windows path escaping for commands

- lua/neo-tree.lua
- lua/neo-tree/setup/init.lua
- lua/neo-tree/ui/renderer.lua
- lua/neo-tree/utils/init.lua
- tests/neo-tree/command/command_current_spec.lua
- tests/neo-tree/command/command_spec.lua
Ref: https://github.com/neovim/neovim/issues/12517
First challenge to workaround new `winfixbuf` option added to nvim-nightly.
Please read the long discussion about this new feature here: https://github.com/vim/vim/pull/13903.
> fix(winfixbuf): avoid windows that have `winfixbuf` when opening buffers

- lua/neo-tree/defaults.lua
Fixes the erroneous ``Some options have changed, please run `:Neotree migrations` to see the changes`` notification when neo-tree is opened. 
Follow up for bug introduced in PR #1372
See https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1372#issuecomment-1995921030 for discussion.
> Delete `enable_normal_mode_for_inputs` from `defaults.lua`

- lua/neo-tree/command/init.lua
I found that when using neo-tree with project.nvim, when changing cwd via project selector, `reveal` argument doesn't work, the file is not focused upon opening the tree. Turns out, project.nvim normalizes disk names on Windows to **lower** case
https://github.com/ahmedkhalf/project.nvim/blob/8c6bad7d22eef1b71144b401c9f74ed01526a4fb/lua/project_nvim/utils/history.lua#L32-L34
As a result, switching directories via project.nvim on Windows results in all file paths having lower case drive letter
Meanwhile, neo-tree normalizes drive names to **upper** case
https://github.com/nvim-neo-tree/neo-tree.nvim/blob/120a83eb7c3c240d5298122111e9f65f0ee5bc8f/lua/neo-tree/utils/init.lua#L792-L793
But it doesn't do so for `reveal_file` argument. Since normalized file names are used as case sensitive ids, …
> fix(command): normalize reveal_file path argument

- doc/neo-tree.txt
- lua/neo-tree/setup/deprecations.lua
- lua/neo-tree/ui/inputs.lua
Closes: #1396
> [!WARNING]
> 
> Breaking change.
> I've deprecated `config.enable_normal_mode_for_inputs` entirely and it does absolutely nothing now.
I've also added examples to the help page.
```lua
{
event = "neo_tree_popup_input_ready",
---@param args { input: NuiInput }
handler = function(args)
-- enter input popup with normal mode by default.
vim.cmd("stopinsert")
-- map <esc> to enter normal mode (closes prompt by default)
args.input:map("i", "<esc>", vim.cmd.stopinsert, { noremap = true })
-- unmap <esc> in normal mode to do nothing (closes prompt by default) (`q` still works)
args.input:map("n", "<esc>", function() end, { noremap = true })
end,
}
```
> fix(input): pass bufnr and winid to event instead

- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
On refresh a list of expanded nodes is gathered to decide what paths to scan. However, when an expanded node lives inside a closed parent node, parent node's number of children will be wrong.
This results in unexpected behavior with `group_with_dirs`, so this fix ensures that all parent nodes are scanned.
For more detailed explanation with screenshots please read: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/833.
Fixes: https://github.com/nvim-neo-tree/neo-tree.nvim/issues/833
> fix(fs_scan): ensure parents of all expanded nodes are also scanned

- lua/neo-tree/ui/renderer.lua
This fixes the bug from #1390, but I have not tested it against `winfixbuf` yet. When you get a chance, can you review and test it? Thanks!
> fix: winfixbuf/`current toggle` bug from #1390

- lua/neo-tree/ui/renderer.lua
Somehow this commit has caused a bug with `:Neotree current toggle`. 
1. If you have more than one split, 
2. and you use `:Neotree current toggle`
3. then open a file
4. then `:Neotree current toggle`
5. you'll get an error (see below)
6. then your current window will be closed
Error from step 5:
```
Error executing vim.schedule lua callback: ...is/.local/share/nvim/lazy/nui.nvim/lua/nui/tree/init.lua:188: missing bufnr                                                     
stack traceback:                                                                                                                                                              
[C]: in function 'error' …
```
> fix(renderer): check if current buffer is loaded

- README.md
- lua/neo-tree/sources/common/filters/init.lua
- lua/neo-tree/sources/filesystem/lib/filter.lua
It's easy for user to custom keymap behavior in fuzzy finder
> feat: allow to pass function to fuzzy_finder_mappings

- lua/neo-tree/sources/buffers/commands.lua
- lua/neo-tree/sources/filesystem/commands.lua
This Pull Request adds features that has been mentioned in #1419, and enhances the functionality of `set_root` for `Neotree buffers` and `Neotree filesystem`.
> feat(set_root): allow filesystem and buffers to run set_root when the cursor is on both files and directories

- lua/neo-tree/ui/renderer.lua
fixes #1415
This reverts the renderer `close` function to ensure that the buffer is deleted synchronously instead of being scheduled for later. That code was originally changed as part of trying to support `winfixbuf`. I have confirmed that the `winfixbuf` situation still works correctly even with this reversion, so the change was never actually needed.
See https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1418#discussion_r1542230720 for more background.
The one known bug that was fixed by the prior code was when you have neotree as the only open window, then open a float neotree and try to open a file. That's an odd edge case and not worth complicating the code base for. If someone can find a **simple** and **obvious** fix for that then we can address it separately.
> fix: revert window close buffer cleanup code

- lua/neo-tree/sources/manager.lua
This is a simple change to fix the `sources.manager.dispose*` functions, which aren't currently working properly.
The bug is a classic remove while looping issue, solved by iterating in reverse. I've just copied the change from the `dispose_invalid_tabs` function.
> fix: sources.manager.dispose* functions not working

- doc/neo-tree.txt
- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/sources/common/preview.lua
I'd like to extend #675 with scrolling capabilities.
1. I took telescope's code for preview scrolling. Code simply sends <C-Y> and <C-E>, nothing complex.
2. Scrolling is performed without focusing the preview window (for me, it's important)
3. Scroll step is configurable
> feat(preview): Scroll Preview window command and bindings

- lua/neo-tree/utils/init.lua
This PR fixes #1448, among other edge cases that weren't previously handled.
Relevant notes were captured in the discussion for #1448, but the gist is that certain punctuation (`[`, `]`, backticks, `$`, etc.) causes Neovim to drop an escaped path separator on Windows. This requires us to use an **additional** `\` (e.g. `X:\[foo]\\\(bar)\baz.txt`).
> fix: handle more edge cases for Windows path escaping

- README.md
Update readme.md to follow PR: https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1395
Delete enable_normal_mode_for_inputs from README example
> Delete enable_normal_mode_for_inputs from README example

- lua/neo-tree/ui/popups.lua
> fix(popups): dont add spacing when the title is empty

- README.md
- doc/neo-tree.txt
- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/file-items.lua
- lua/neo-tree/sources/filesystem/init.lua
Implementing the option requested in the issue #1255. Tested on my neovim setup and seems to work.
I've worked very little on neovim plugins so if i've missed to add something please point it out!
> feat: add options always_show_by_pattern

- README.md
- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/components.lua
- lua/neo-tree/sources/document_symbols/components.lua
This supersedes #1510 
Previously I looked at adding direct support for `mini.icons` into the code base. @miversen33 made a fantastic point that it seems like icon providing is a simple pattern that can grow arbitrarily and it might make sense to make it configurable by the user to provide their own icon provider for components. This adds a new section to the common section of the components to utilize an icon provider for resolving icons based on a node/state.
I took a look at the `document_symbols` component and I'm honestly not sure what the best approach for that part is. Should we try to unify it with the component's icon provider and have it override it to an icon provider of LSP kinds or should we make a new config option specifically for that component that has a similar pattern? …
> feat: add `icon.provider` option to components for full control

- lua/neo-tree/sources/common/hijack_cursor.lua
I've been getting a crash with certain directories because it's possible for the state table to not contain a tree temporarily. This fixes the issue.
> Check for nil state.tree

- lua/neo-tree/sources/manager.lua
fix https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1067
Probably, neovim does not fire the `TabClosed` autocmd in some conditions.
So invalid tabs might be remained to the manager states.
check & dispose invalid states before enumerate it.
> fix: remove invalid_tabs before _for_each_state

- doc/neo-tree.txt
- lua/neo-tree/defaults.lua
- lua/neo-tree/ui/renderer.lua
Hello 👋
Love the plugin, spend so much of my dev time using it, so I thought I'd contribute a feature I really wanted.
Allows you to specify a function in your config that takes the state and resolves a popup title. Since it's a function you can even add stateful data if you really wished. Of course the current defaults are respected and this shouldn't have any breaking changes.
> feat(popups): Add title formatting option

- lua/neo-tree/git/status.lua
`schedule_wrap` floods the event loop with work that could've been done right away much faster here. massive improvement with my goofy git repo $HOME without a .gitignore
> fix: terrible git status performance in large repo

- README.md
- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/components.lua
I've added a `width` field to the configs so that the width of the columns displayed in the file explorer can be customised. Text that are too long are also truncated with `…` to prevent the columns from being offset.
Edit: `vim.fn.printf` is used instead of `string.format` to prevent an error when the width is more than 99.
Demo:
```lua
default_component_configs = {
last_modified = {
width = 10,
},
created = {
enabled = true,
width = 30,
},
},
})
```
This is the fix mentioned in #1614.
> feat(filesystem): Customisable column width

- lua/neo-tree/sources/buffers/lib/items.lua
- lua/neo-tree/sources/common/file-items.lua
Firstly, for my first contribution to neo-tree, I would like to thank the neo-tree maintainers for producing an such an awesome piece of software. Neo-tree is an integral part of my experience with Neovim as my daily driver, and an amazing example of the wider Neovim ecosystem. I also thank the maintainers for the opportunity to contribute, and welcome any feedback on my contributions.
----------
Paths should be normalized when: 
- Checking their membership in the root directory, and 
- Acquiring their parent paths 
before adding them to the buffers source.
This PR fixes issue #1617.
> fix(buffers): Normalize paths for buffers source

- doc/neo-tree.txt
- lua/neo-tree/command/init.lua
This reverts commit 385270ea21a53e06d7fff4730996bd0bb220255d.
https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1501
> Revert "fix(command): allow reveal_file to be used with dir (#1501)"

- lua/neo-tree/ui/renderer.lua
Would fix: #1413 
Allowing a custom desc to be passed when sending a keymap instead of just defaulting to the `command passed`
Ex: Sending `{ 'diff_files', desc = "Diff Two Files' }` would now set the help text to "Diff Two Files" instead of "diff_files"
> feat: support desc for string command keymaps

- lua/neo-tree/sources/common/help.lua
When a lower fold level is set the help menu content folds and because of the keybindings you cannot easily unfold things. To avoid this we disable folding in the help popup window.
https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1476
> fix:foldlevel breaks help display (#1476)

- lua/neo-tree/sources/git_status/init.lua
- lua/neo-tree/sources/git_status/lib/items.lua
should close #1309
now this should work
```lua
{
"<leader>ge",
function()
require("neo-tree.command").execute({
toggle = true,
dir = LazyVim.root(), -- or comment it, then cwd becomes default
source = "git_status",
})
end,
desc = "Git Explorer",
},
```
> Fix(git_status): respect `dir` parameter passed into command

- lua/neo-tree/command/init.lua
This PR changes the behaviour of the command when used with `dir` option.
With this change the root/cwd will be set to `dir` if the revealing file is a children of the `dir`, otherwise the root/cwd will be set to the directory of the revealing file.
related PR/issues:
https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1500
https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1501
> fix(command): allow reveal_file to be used with dir

- lua/neo-tree/sources/common/preview.lua
Fixes half of #514 - at least the "moving up" part.
It seems that the added `-1` here was exactly what moved the floating window by 1 each time a preview window was created. Seems to work correctly without it in float and non-float mode.
To check, set neo tree to float and toggle preview on a file several times with and without this fix.
> fix(preview): stop preview from moving floating tree

- README.md
- doc/neo-tree.txt
- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/sources/common/components.lua
- lua/neo-tree/utils/init.lua
I've added a `format` field in the configs for the components `last_modified` and `created` so that users can change the format string used to display timestamps in the file explorer. The field also accepts a function that returns a string so that features like relative timestamps can be implemented. The change is also applied to the file details popup window.
Here's an example setup:
```lua
default_component_configs = {
last_modified = {
enabled = true,
format = function(seconds)
local now = os.time()
local diff = now - seconds
local function pluralise(value, unit)
return value .. " " .. unit .. (value == 1 and "" or "s") .. " ago"
end
if diff < 60 then
return "Just now"
elseif diff < 3600 then
local minutes = math.floor(diff / 60)
return pluralise(minutes, …
```
> feat(filesystem): customizable timestamp formats

- lua/neo-tree/utils/init.lua
- tests/neo-tree/utils/path_spec.lua
I noticed that when I renamed a file in neo-tree some of my opened buffers got changed weirdly. I tracked this to the is_subpath function.
The problem is with the following example
```
/home/user/project/file
/home/user/project/file_for_example
```
These paths would be matched as a correct subpath, even though they aren't.
I added a simple check I believe fixes this issue
> fix(utils): handle edge case for `is_subpath`

- README.md
- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/filesystem/lib/filter.lua
Useful for users who wants to map something else than `<esc>` (e.g. `<C-e>` or `<C-c>)` to close the fuzzy finder input window
> feat: add close to fuzzy_finder_mappings

- lua/neo-tree/sources/filesystem/lib/filter_external.lua
Not sure what was the purpose of that exclusion, but it was causing issues when `find` command is used within `filter` logic. 
```lua
if not ignore.dotfiles then
append("-not", "-path", "*/.*")
end
```
You would expect that when `ignore-dotfiles` is `false` you don't want to exclude dot files and directories. In fact it was not just excluding dot files, but all the other valid options if current `path` contains any `.` directories. For example for me the resulting command was
```bash
find  "/Users/nouwa/.config/nvim" -not -path '*/.*' -iname "*lua*"
```
and because my path has `.config` -- all files were excluded, producing empty search result.
Once this section removed, eveyrhing works as expected with both `ignore.dotfiles = true` and `false`.
> fix(filesystem): ignore dotfiles properly for find filter

- lua/neo-tree/sources/common/preview.lua
@pynappo
This is the exact same pr like john-h-k/neo-tree.nvim#1.
Edit: It would be great if there would be some kind of directory preview (with eza/lsd/ls/tree), but that's mostly certainly something for a separate pr. (I did look into this but couldn't find the correct place in the code to implement this)
> fix(preview): allow enabling when node is directory

- lua/neo-tree/sources/document_symbols/lib/symbols_utils.lua
The former is only available in v0.10 upwards and i believe neo-tree still supports neovim v0.9. but to prevent deprecation warnings we should prefer the former over the latter when possible.
Closes #1551.
> fix(lsp): prefer `get_clients` over `get_active_clients`

- lua/neo-tree/sources/common/help.lua
> fix(help): clamp help window size on VimResized

- README.md
Not sure if this is a good idea, but I find the longer example section in the README too long to scroll through, making it hard to get to the next part of the guide.
> doc: make longer example collapsible

- .github/workflows/ci.yml
- .stylua.toml
- lua/neo-tree/setup/init.lua
- lua/neo-tree/sources/buffers/init.lua
- lua/neo-tree/sources/common/components.lua
- lua/neo-tree/sources/common/container.lua
- lua/neo-tree/sources/common/filters/filter_fzy.lua
- lua/neo-tree/sources/common/hijack_cursor.lua
- lua/neo-tree/sources/common/node_expander.lua
- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
- lua/neo-tree/sources/git_status/init.lua
- lua/neo-tree/sources/manager.lua
- lua/neo-tree/ui/highlights.lua
- lua/neo-tree/ui/renderer.lua
- lua/neo-tree/ui/selector.lua
- lua/neo-tree/utils/filesize/filesize.lua
- tests/neo-tree/sources/manager_spec.lua
just testing cause it seems like stylua isn't really applying?
> chore: update stylua action and format

- lua/neo-tree.lua
- lua/neo-tree/command/completion.lua
- lua/neo-tree/setup/init.lua
- lua/neo-tree/setup/netrw.lua
- lua/neo-tree/utils/init.lua
- plugin/neo-tree.lua
- plugin/neo-tree.vim
- tests/mininit.lua
- tests/utils/init.lua
neo-tree has a ton of configuration, so sometimes merging the config table takes a significant portion of startup time. This leads to people lazy-loading neo-tree which sometimes causes issues to be filed, mostly with netrw hijacking. This PR defers the merging until:
- When netrw may need to be hijacked
- `:Neotree` command parsing/execution
On my machine, this reduces startuptime to ~2-3ms when it was previously ~30ms.
Some precautions are taken to prevent breaking people's setups who already lazy-load neo-tree.
Also turned the plugin file to lua because it's easier for me to work with.
Edit: fixed a bug where `source=` cmdline completion wouldn't work.
> fix(setup): defer merging config until needed

- README.md
- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/utils/init.lua
fix https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1561
Both NvimTree and NERDTree open files with relative paths by default.
> feat: add open_files_using_relative_paths option

- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
Closes #1556
edit: Was considering making utils.normalize_path call vim.fs.normalize on linux with this PR but for safety probably best to see if other similar issues occur before doing that.
> fix(fs_actions): normalize the move destination

- lua/neo-tree/sources/common/container.lua
- lua/neo-tree/ui/renderer.lua
- lua/neo-tree/ui/selector.lua
- lua/neo-tree/utils/init.lua
Fixes #1619.
- missing right side git status symbol for the middle file
- truncation is mid-character for the bottom file
- Fading isn't great on non-ascii:
- Looks like padding needs to be added for wide characters:
Also idk if this is an issue with this PR or neo-tree (might just be exacerbated due to the more intensive truncation), but changing the width repeatedly, really quickly, seems to cause the neo-tree window to scroll horizontally?
tagging @Emptyfruit if they'd like to test this out.
> fix(container): truncate text by cell width/characters

- lua/neo-tree.lua
- plugin/neo-tree.lua
fixing #1658 
issue being that try_netrw_hijack should not run instantly on setup, else it always has open_default behavior if you don't lazy-load neo-tree
> fix(setup): defer hijack until setup or BufEnter

- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/sources/common/components.lua
- lua/neo-tree/sources/manager.lua
Expands #1694 
> Currently, `order_by_name` does not respect sort direction.
This addition would add support to toggle between ascending & descending name sort.
* Updates the state creation with a default sort of `{ label = "Name", direction = 1 }`
* This prevents needing to send the `order_by_name` command twice to reverse sort order
* Adds a sort icon to the "Name" column when in "window" view
* Should not apply to the "tab" view
> feat(commands): Add descending order_by_name support

- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
Fix for `bad argument to fs_state` error when cutting and pasting on Windows.
Closes #1693
> fix(fs_actions): windowize paths on windows before moving

- lua/neo-tree/defaults.lua
This fixes an issue where the `document_symbols` mode had an invalid mapping from the global map, ie. the `["b"] = "rename_basename"` mapping.
The approach is to move the global mapping `["b"] = "rename_basename"` mapping to each of the more specific `git_status`, `buffers`, and `filesystem` mappings, where they are valid.
When pressing `b` in the `document_symbols` tree, I was getting this message:
```
[Neo-tree WARN] Invalid mapping for  b :  nil
```
And when pressing `?` to see the keymap, I ran into this red error message:
```
E5108: Error executing lua: ...ng/.local/share/nvim/lazy/nui.nvim/lua/nui/line/init.lua:22: attempt to index local 'block' (a nil value)                                                                                                stack traceback: …
```
> fix(defaults): skip rename_basename in document_symbols mapping

- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/sources/common/preview.lua
- lua/neo-tree/ui/renderer.lua
Follow-up for #1651
Closes #1707 
Closes #1710 (maybe?)
> fix(command): redo fallback mechanism

- lua/neo-tree.lua
- lua/neo-tree/setup/deprecations.lua
- lua/neo-tree/setup/init.lua
- lua/neo-tree/setup/netrw.lua
- lua/neo-tree/sources/common/commands.lua
- lua/neo-tree/sources/common/preview.lua
- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
- lua/neo-tree/ui/highlights.lua
- lua/neo-tree/ui/renderer.lua
- lua/neo-tree/utils/init.lua
- tests/neo-tree/sources/filesystem/filesystem_netrw_hijack_spec.lua
- tests/utils/verify.lua
part of an effort to cleanup the codebase
> refactor: use vim.{bo/wo/go/o} for options

- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
> fix(fs_actions): fix move/rename check

- lua/neo-tree/setup/netrw.lua
should fix a regression with some lazyloading configs (lazyvim) and bind_to_cwd = false
> fix(setup): hijack on bufname instead of path

- lua/neo-tree.lua
- lua/neo-tree/defaults.lua
- lua/neo-tree/types/config.lua
as of last month, lua_ls has a convenient (partial) class type which lets us be more sure about the values in neotree's actual config while being less sure about the user's passed in config
> refactor(types): change `neotree.Config` to a partial class

- lua/neo-tree/sources/manager.lua
- tests/neo-tree/manager/state_spec.lua
> fix(manager): ensure setup before creating state

- lua/neo-tree/sources/filesystem/lib/fs_scan.lua
In `sync_scan`, if `fs_opendir` errors then it will still try to run `fs_closedir(dir)`, causing an error since `dir` is `nil`. The easiest way to reproduce the issue is to create a folder and remove all its permissions, then try to navigate to it in neo-tree.
I've also removed the `pcall`'s around the uv functions, which are unnecessary since errors are returned rather than being "thrown".
> fix(filesystem): don't try to close nil dir

- .github/workflows/.luarc-5.1.json
- .github/workflows/.luarc-luajit-master.json
- .github/workflows/luals-check.yml
- .luarc.json
- Makefile
- lua/neo-tree/events/init.lua
- lua/neo-tree/events/queue.lua
- lua/neo-tree/sources/common/container.lua
- lua/neo-tree/sources/common/file-nesting.lua
- lua/neo-tree/sources/common/preview.lua
- lua/neo-tree/sources/document_symbols/lib/client_filters.lua
- lua/neo-tree/sources/document_symbols/lib/symbols_utils.lua
- lua/neo-tree/sources/filesystem/lib/filter.lua
- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
- lua/neo-tree/types/fixes/compat-0.10.lua
- lua/neo-tree/ui/highlights.lua
- lua/neo-tree/ui/renderer.lua
- lua/neo-tree/utils/init.lua
- mise.toml
Closes https://github.com/nvim-neo-tree/neo-tree.nvim/issues/1330
> fix: remove gotos, use newer functions, fix types

- Dockerfile
uses alpine and splits the dockerfile into a build-neovim phase and a clone-plugins phase, making images much smaller outside of building neovim
> build: slim down Dockerfile

- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
- lua/neo-tree/utils/init.lua
**helloworld.c** and **Helloworld.c** are recognized as the same file
I found a small issue with neo-tree. For example, if your file is named:
`helloworld.c`
and you want to rename it to:
`Helloworld.c`
you will get the ` warning: already exists, canceling`.
---
Neovim version information:
```
NVIM v0.10.4
Build type: Release
LuaJIT 2.1.1741730670
Run ":verbose version" for more info
```
---
System info:
```
Darwin IUSX 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:11 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6020 arm64
```
I know this issue doesn’t exist on Linux, but it does exist on my macOS system. This PR might have some issues, but it works fine on my system and fixes the problem. However, the code might not be very elegant.
> fix(filesystem): handle case-insensitive renames on all OSs

- README.md
- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/preview.lua
- lua/neo-tree/types/config.lua
- lua/neo-tree/ui/inputs.lua
- lua/neo-tree/ui/popups.lua
Closes #1743
~~currently not working as intended, see: https://github.com/MunifTanjim/nui.nvim/pull/403~~
> feat(popup): support 'winborder' with `popup_border_style = ""`

- lua/neo-tree/setup/init.lua
fixes integration with nvim-lsp-file-operations
Closes #1782
> fix(events): don't clear before events are defined

- lua/neo-tree/ui/renderer.lua
This fixes stack overflow when cutting and pasting a file with 'hide_root_node = true' (#1517). The renderer was trying to focus a hidden root node.
> fix(renderer): fix cut & paste stack overflow on hidden root

- lua/neo-tree.lua
- lua/neo-tree/setup/init.lua
- plugin/neo-tree.lua
> fix: implement proper check for `close_if_last_window`

- doc/neo-tree.txt
> docs: remove double 'the'

- plugin/neo-tree.lua
Closes #1836 
Apparently when a quit isn't scheduled it prevents leaving autocmds from working.
> fix: schedule quit for `close_if_last_window`

- lua/neo-tree/ui/renderer.lua
- tests/neo-tree/command/command_spec.lua
Resolves this regression https://github.com/nvim-neo-tree/neo-tree.nvim/pull/1838#issuecomment-3240307703
CursorMoved is apparently not emitted in headless mode, which is why the tests didn't catch this regression. A new test has been added to cover this regression.
> fix(renderer): don't clear node id focus on CursorMoved

- lua/neo-tree/sources/filesystem/commands.lua
> fix(commands): exclude untracked files from next_git_modified

- lua/neo-tree/log.lua
- lua/neo-tree/sources/filesystem/lib/fs_actions.lua
- lua/neo-tree/types/fixes/uv.lua
- lua/neo-tree/utils/init.lua
- tests/neo-tree/utils/fs_spec.lua
> fix(fs_actions): prevent copy/move to child, allow link copies

- LICENSE
- lua/neo-tree/health/init.lua
- lua/neo-tree/log.lua
Closes #1882 
with noice and close_with_last_window there was an error happening on exit that's hard to notice otherwise.
> fix(log): close log file later

- README.md
- lua/neo-tree/defaults.lua
- lua/neo-tree/sources/common/components.lua
Closes #1059 
Closes #1486
Closes #1493 
Arguably icons shouldn't be dimmed by default but maybe leave that for 4.0?
> feat(common): option for filenames/icons to ignore filtered hls
